import type { Menu } from '../../identity/contracts';
import { SEED_DATE } from '../_base';

/** CMS 内容管理（14000 段） */
export const SEED_MENUS_CMS: Menu[] = [
  { id: 14000, parentId: 0, title: 'CMS 内容管理', name: 'CmsCenter', icon: 'Newspaper', type: 'directory', sort: 15, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14010, parentId: 14000, title: '数据看板', name: 'CmsDashboard', path: '/cms/dashboard', component: 'cms/CmsDashboardPage', icon: 'LayoutDashboard', type: 'menu', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14020, parentId: 14000, title: '站点管理', name: 'CmsSites', path: '/cms/sites', component: 'cms/SitesPage', icon: 'Globe', type: 'menu', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14030, parentId: 14000, title: '栏目管理', name: 'CmsChannels', path: '/cms/channels', component: 'cms/ChannelsPage', icon: 'FolderTree', type: 'menu', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14040, parentId: 14000, title: '内容管理', name: 'CmsContents', path: '/cms/contents', component: 'cms/ContentsPage', icon: 'FileText', type: 'menu', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14050, parentId: 14040, title: '内容编辑页', name: 'CmsContentEdit', path: '/cms/contents/edit', component: 'cms/ContentEditPage', icon: 'FilePen', type: 'menu', sort: 7, status: 'enabled', visible: false, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14060, parentId: 14000, title: '素材中心', name: 'CmsResources', path: '/cms/resources', component: 'cms/ResourcesPage', icon: 'Image', type: 'menu', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14070, parentId: 14000, title: '内容模型', name: 'CmsModels', path: '/cms/models', component: 'cms/ModelsPage', icon: 'Blocks', type: 'menu', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14080, parentId: 14000, title: '标签管理', name: 'CmsTags', path: '/cms/tags', component: 'cms/TagsPage', icon: 'Tags', type: 'menu', sort: 5, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14090, parentId: 14000, title: '内容工作台', name: 'CmsWorkspace', path: '/cms/workspace', component: 'cms/CmsWorkspacePage', icon: 'ClipboardList', type: 'menu', sort: 6, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14100, parentId: 14000, title: '友情链接', name: 'CmsFriendLinks', path: '/cms/friend-links', component: 'cms/FriendLinksPage', icon: 'Link2', type: 'menu', sort: 7, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14110, parentId: 14000, title: '检索管理', name: 'CmsSearch', path: '/cms/search', component: 'cms/SearchAdminPage', icon: 'SearchCheck', type: 'menu', sort: 9, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14120, parentId: 14000, title: 'SEO 管理', name: 'CmsSeo', path: '/cms/seo', component: 'cms/SeoPage', icon: 'TrendingUp', type: 'menu', sort: 10, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14130, parentId: 14000, title: '评论管理', name: 'CmsComments', path: '/cms/comments', component: 'cms/CommentsPage', icon: 'MessageSquare', type: 'menu', sort: 11, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14140, parentId: 14000, title: '广告管理', name: 'CmsAds', path: '/cms/ads', component: 'cms/AdsPage', icon: 'Megaphone', type: 'menu', sort: 12, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14150, parentId: 14000, title: '表单管理', name: 'CmsForms', path: '/cms/forms', component: 'cms/FormsPage', icon: 'ClipboardList', type: 'menu', sort: 13, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14160, parentId: 14000, title: '敏感词库', name: 'CmsSensitiveWords', path: '/cms/sensitive-words', component: 'cms/SensitiveWordsPage', icon: 'ShieldAlert', type: 'menu', sort: 14, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14170, parentId: 14000, title: '采集中心', name: 'CmsCollect', path: '/cms/collect', component: 'cms/CollectPage', icon: 'Download', type: 'menu', sort: 15, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14300, parentId: 14000, title: '页面部件', name: 'CmsWidgets', path: '/cms/widgets', component: 'cms/WidgetsPage', icon: 'PanelsTopLeft', type: 'menu', sort: 16, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14310, parentId: 14300, title: '页面部件编辑', name: 'CmsWidgetEdit', path: '/cms/widgets/edit', component: 'cms/WidgetEditPage', icon: 'SquarePen', type: 'menu', sort: 7, status: 'enabled', visible: false, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14180, parentId: 14000, title: '页面搭建', name: 'CmsPages', path: '/cms/pages', component: 'cms/PagesPage', icon: 'LayoutTemplate', type: 'menu', sort: 17, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14200, parentId: 14000, title: '易错词库', name: 'CmsErrorProneWords', path: '/cms/error-prone-words', component: 'cms/ErrorProneWordsPage', icon: 'SpellCheck', type: 'menu', sort: 18, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14210, parentId: 14000, title: '互动问卷', name: 'CmsInteractions', path: '/cms/interactions', component: 'cms/SurveysPage', icon: 'ListChecks', type: 'menu', sort: 19, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14216, parentId: 14210, title: '互动问卷设计页', name: 'CmsInteractionEdit', path: '/cms/interactions/edit', component: 'cms/interaction/InteractionEditPage', icon: 'PencilRuler', type: 'menu', sort: 5, status: 'enabled', visible: false, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14220, parentId: 14000, title: '访问统计', name: 'CmsStats', path: '/cms/stats', component: 'cms/StatsPage', icon: 'ChartLine', type: 'menu', sort: 20, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14240, parentId: 14000, title: '发布中心', name: 'CmsPublishing', path: '/cms/publishing', component: 'cms/PublishingPage', icon: 'Rocket', type: 'menu', sort: 22, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14250, parentId: 14000, title: '会员订阅', name: 'CmsSubscriptions', path: '/cms/subscriptions', component: 'cms/SubscriptionsPage', icon: 'BellRing', type: 'menu', sort: 23, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 14260, parentId: 14000, title: '内容分发', name: 'CmsDistribution', path: '/cms/distribution', component: 'cms/DistributionPage', icon: 'Network', type: 'menu', sort: 24, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
];
