import type { Menu } from '../../identity/contracts';
import { SEED_DATE } from '../_base';

/** 系统设置（2000 段） */
export const SEED_MENUS_SETTINGS: Menu[] = [
  { id: 2000, parentId: 0, title: '系统设置', name: 'SystemSettings', icon: 'Settings2', type: 'directory', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2010, parentId: 2000, title: '系统设置', name: 'SystemSettingsCenter', path: '/system/settings', component: 'system/settings/SettingsPage', icon: 'SlidersHorizontal', type: 'menu', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2011, parentId: 2010, title: '查看设置', type: 'button', permission: 'system:setting:view', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2012, parentId: 2010, title: '修改设置', type: 'button', permission: 'system:setting:update', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2020, parentId: 2000, title: '身份安全', name: 'SystemIdentitySecurity', path: '/system/identity-security', component: 'system/identity-security/IdentitySecurityPage', icon: 'Fingerprint', type: 'menu', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2021, parentId: 2020, title: '管理策略', type: 'button', permission: 'system:identity-security:manage', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2030, parentId: 2000, title: '企业身份源', name: 'SystemIdentityProviders', path: '/system/identity-providers', component: 'system/identity-providers/IdentityProvidersPage', icon: 'Building2', type: 'menu', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2031, parentId: 2030, title: '管理身份源', type: 'button', permission: 'system:identity-provider:manage', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },

  // ─── 通讯录同步（2610-2643）────────────────────────────────────────────────
  { id: 2610, parentId: 2000, title: '通讯录同步', name: 'SystemDirectorySync', icon: 'FolderSync', type: 'directory', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2620, parentId: 2610, title: '同步源配置', name: 'DirectorySyncSources', path: '/system/directory-sync/sources', component: 'system/directory-sync/DirectorySyncSourcesPage', icon: 'PlugZap', type: 'menu', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2621, parentId: 2620, title: '查询', type: 'button', permission: 'system:dirsync-source:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2622, parentId: 2620, title: '新增源', type: 'button', permission: 'system:dirsync-source:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2623, parentId: 2620, title: '编辑源', type: 'button', permission: 'system:dirsync-source:edit', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2624, parentId: 2620, title: '删除源', type: 'button', permission: 'system:dirsync-source:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2625, parentId: 2620, title: '测试连接', type: 'button', permission: 'system:dirsync-source:test', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2626, parentId: 2620, title: '预览差异', type: 'button', permission: 'system:dirsync-source:preview', sort: 5, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2627, parentId: 2620, title: '立即同步', type: 'button', permission: 'system:dirsync-source:run', sort: 6, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2630, parentId: 2610, title: '同步记录', name: 'DirectorySyncLogs', path: '/system/directory-sync/logs', component: 'system/directory-sync/DirectorySyncLogsPage', icon: 'History', type: 'menu', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2631, parentId: 2630, title: '查询', type: 'button', permission: 'system:dirsync-log:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2632, parentId: 2630, title: '查看差异', type: 'button', permission: 'system:dirsync-log:detail', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2633, parentId: 2630, title: '重试失败项', type: 'button', permission: 'system:dirsync-log:retry', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2640, parentId: 2610, title: '冲突处理', name: 'DirectorySyncConflicts', path: '/system/directory-sync/conflicts', component: 'system/directory-sync/DirectorySyncConflictsPage', icon: 'GitMerge', type: 'menu', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2641, parentId: 2640, title: '查询', type: 'button', permission: 'system:dirsync-conflict:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2642, parentId: 2640, title: '裁决', type: 'button', permission: 'system:dirsync-conflict:resolve', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2643, parentId: 2640, title: '批量忽略', type: 'button', permission: 'system:dirsync-conflict:ignore', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2040, parentId: 2000, title: '文件管理', name: 'SystemFiles', icon: 'FolderOpen', type: 'directory', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2041, parentId: 2040, title: '查询', type: 'button', permission: 'system:file:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2050, parentId: 2040, title: '文件配置', name: 'SystemFileConfigs', path: '/system/file-configs', component: 'system/file-configs/FileStorageConfigsPage', icon: 'HardDriveUpload', type: 'menu', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2051, parentId: 2050, title: '查询', type: 'button', permission: 'system:file:config', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2052, parentId: 2050, title: '新增配置', type: 'button', permission: 'system:file:config:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2053, parentId: 2050, title: '编辑配置', type: 'button', permission: 'system:file:config:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2054, parentId: 2050, title: '删除配置', type: 'button', permission: 'system:file:config:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2055, parentId: 2050, title: '设为默认', type: 'button', permission: 'system:file:config:default', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2060, parentId: 2040, title: '文件列表', name: 'SystemFileList', path: '/system/files', component: 'system/files/FilesPage', icon: 'Files', type: 'menu', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2061, parentId: 2060, title: '查询', type: 'button', permission: 'system:file:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2062, parentId: 2060, title: '上传文件', type: 'button', permission: 'system:file:upload', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2063, parentId: 2060, title: '删除文件', type: 'button', permission: 'system:file:delete', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2070, parentId: 2000, title: 'OAuth配置', name: 'SystemOAuthConfig', path: '/system/oauth-config', component: 'system/oauth-config/OAuthConfigPage', icon: 'KeyRound', type: 'menu', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2071, parentId: 2070, title: '查询', type: 'button', permission: 'system:oauth-config:view', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2072, parentId: 2070, title: '保存配置', type: 'button', permission: 'system:oauth-config:update', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2080, parentId: 2000, title: '服务监控', name: 'SystemMonitor', path: '/system/monitor', component: 'system/monitor/MonitorPage', icon: 'Activity', type: 'menu', sort: 5, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2081, parentId: 2080, title: '查询', type: 'button', permission: 'system:monitor:view', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2090, parentId: 2000, title: '在线用户', name: 'SystemSessions', path: '/system/sessions', component: 'system/sessions/OnlineSessionsPage', icon: 'MonitorSmartphone', type: 'menu', sort: 6, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2091, parentId: 2090, title: '查询', type: 'button', permission: 'system:session:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2092, parentId: 2090, title: '强制下线', type: 'button', permission: 'system:session:forceLogout', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2100, parentId: 2000, title: '定时任务', name: 'SystemCronJobs', path: '/system/cron-jobs', component: 'system/cron-jobs/CronJobsPage', icon: 'Clock', type: 'menu', sort: 7, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2101, parentId: 2100, title: '查询', type: 'button', permission: 'system:cronjob:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2102, parentId: 2100, title: '新增任务', type: 'button', permission: 'system:cronjob:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2103, parentId: 2100, title: '编辑任务', type: 'button', permission: 'system:cronjob:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2104, parentId: 2100, title: '删除任务', type: 'button', permission: 'system:cronjob:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2105, parentId: 2100, title: '立即执行', type: 'button', permission: 'system:cronjob:execute', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2110, parentId: 2000, title: '数据库备份', name: 'SystemDbBackups', path: '/system/db-backups', component: 'system/db-backups/DbBackupsPage', icon: 'DatabaseBackup', type: 'menu', sort: 8, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2111, parentId: 2110, title: '查询', type: 'button', permission: 'system:db-backup:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2112, parentId: 2110, title: '创建备份', type: 'button', permission: 'system:db-backup:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2113, parentId: 2110, title: '删除备份', type: 'button', permission: 'system:db-backup:delete', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2120, parentId: 2000, title: '审计日志', name: 'SystemAuditLogs', icon: 'ClipboardMinus', type: 'directory', sort: 9, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2130, parentId: 2120, title: '登录日志', name: 'SystemLoginLogs', path: '/system/login-logs', component: 'system/login-logs/LoginLogsPage', icon: 'List', type: 'menu', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2131, parentId: 2130, title: '查询', type: 'button', permission: 'system:log:login', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2140, parentId: 2120, title: '操作日志', name: 'SystemOperationLogs', path: '/system/operation-logs', component: 'system/operation-logs/OperationLogsPage', icon: 'ClipboardList', type: 'menu', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2141, parentId: 2140, title: '查询', type: 'button', permission: 'system:log:operation', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2150, parentId: 2120, title: '日志文件', name: 'SystemLogFiles', path: '/system/log-files', component: 'system/log-files/LogFilesPage', icon: 'FileText', type: 'menu', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2151, parentId: 2150, title: '查看日志', type: 'button', permission: 'system:log:files', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2152, parentId: 2150, title: '下载日志', type: 'button', permission: 'system:log:files:download', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2153, parentId: 2150, title: '删除日志', type: 'button', permission: 'system:log:files:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2720, parentId: 2120, title: '链路追踪', name: 'SystemTrace', path: '/system/trace', component: 'system/trace/TracePage', icon: 'Route', type: 'menu', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2721, parentId: 2720, title: '查询', type: 'button', permission: 'system:trace:view', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2730, parentId: 2000, title: '导入中心', name: 'SystemImportCenter', path: '/system/import-center', component: 'system/import-center/ImportCenterPage', icon: 'Upload', type: 'menu', sort: 19, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2731, parentId: 2730, title: '查询', type: 'button', permission: 'system:import-job:view', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2160, parentId: 2000, title: '公告管理', name: 'SystemAnnouncements', path: '/system/announcements', component: 'system/announcements/AnnouncementsPage', icon: 'Megaphone', type: 'menu', sort: 10, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2161, parentId: 2160, title: '查询', type: 'button', permission: 'system:announcement:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2162, parentId: 2160, title: '新增公告', type: 'button', permission: 'system:announcement:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2163, parentId: 2160, title: '编辑公告', type: 'button', permission: 'system:announcement:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2164, parentId: 2160, title: '删除公告', type: 'button', permission: 'system:announcement:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2170, parentId: 2000, title: 'IP访问控制', name: 'SystemIpAccess', path: '/system/ip-access', component: 'system/ip-access/IpAccessPage', icon: 'ShieldBan', type: 'menu', sort: 11, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2171, parentId: 2170, title: '查询', type: 'button', permission: 'system:ip-access:view', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2172, parentId: 2170, title: '保存配置', type: 'button', permission: 'system:ip-access:update', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2173, parentId: 2170, title: '查看拦截日志', type: 'button', permission: 'system:ip-access:log', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2180, parentId: 2000, title: '意见反馈', name: 'SystemFeedbacks', path: '/system/feedbacks', component: 'system/feedbacks/FeedbacksPage', icon: 'MessageSquareHeart', type: 'menu', sort: 11, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2181, parentId: 2180, title: '查询', type: 'button', permission: 'system:feedback:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2182, parentId: 2180, title: '处理反馈', type: 'button', permission: 'system:feedback:handle', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2183, parentId: 2180, title: '删除反馈', type: 'button', permission: 'system:feedback:delete', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2190, parentId: 2000, title: '缓存管理', name: 'SystemCache', path: '/system/cache', component: 'system/cache/CacheManagePage', icon: 'BrainCircuit', type: 'menu', sort: 12, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2191, parentId: 2190, title: '查询', type: 'button', permission: 'system:cache:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2192, parentId: 2190, title: '删除缓存', type: 'button', permission: 'system:cache:delete', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2193, parentId: 2190, title: '编辑缓存', type: 'button', permission: 'system:cache:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2200, parentId: 2000, title: '通知管理', name: 'SystemNotification', icon: 'BellRing', type: 'directory', sort: 13, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2210, parentId: 2200, title: '邮件管理', name: 'NotificationEmail', icon: 'Mail', type: 'directory', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2220, parentId: 2210, title: '邮件配置', name: 'NotificationEmailConfig', path: '/system/email-config', component: 'system/email-config/EmailConfigPage', icon: 'MailCheck', type: 'menu', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2221, parentId: 2220, title: '查询', type: 'button', permission: 'system:email-config:view', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2222, parentId: 2220, title: '保存配置', type: 'button', permission: 'system:email-config:update', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2223, parentId: 2220, title: '测试邮件', type: 'button', permission: 'system:email-config:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2230, parentId: 2210, title: '邮件模板', name: 'NotificationEmailTemplates', path: '/system/email-templates', component: 'system/email-templates/EmailTemplatesPage', icon: 'MailPlus', type: 'menu', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2231, parentId: 2230, title: '查询', type: 'button', permission: 'system:email-template:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2232, parentId: 2230, title: '新增模板', type: 'button', permission: 'system:email-template:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2233, parentId: 2230, title: '编辑模板', type: 'button', permission: 'system:email-template:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2234, parentId: 2230, title: '删除模板', type: 'button', permission: 'system:email-template:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2240, parentId: 2210, title: '邮件发送记录', name: 'NotificationEmailSendLogs', path: '/system/email-send-logs', component: 'system/email-send-logs/EmailSendLogsPage', icon: 'MailX', type: 'menu', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2241, parentId: 2240, title: '查询', type: 'button', permission: 'system:email-send-log:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2242, parentId: 2240, title: '删除记录', type: 'button', permission: 'system:email-send-log:delete', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2243, parentId: 2240, title: '导出记录', type: 'button', permission: 'system:email-send-log:export', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2250, parentId: 2200, title: '短信管理', name: 'NotificationSms', icon: 'MessageSquareText', type: 'directory', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2260, parentId: 2250, title: '短信配置', name: 'NotificationSmsConfigs', path: '/system/sms-configs', component: 'system/sms-configs/SmsConfigsPage', icon: 'Smartphone', type: 'menu', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2261, parentId: 2260, title: '查询', type: 'button', permission: 'system:sms-config:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2262, parentId: 2260, title: '新增配置', type: 'button', permission: 'system:sms-config:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2263, parentId: 2260, title: '编辑配置', type: 'button', permission: 'system:sms-config:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2264, parentId: 2260, title: '删除配置', type: 'button', permission: 'system:sms-config:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2265, parentId: 2260, title: '设为默认', type: 'button', permission: 'system:sms-config:default', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2270, parentId: 2250, title: '短信模板', name: 'NotificationSmsTemplates', path: '/system/sms-templates', component: 'system/sms-templates/SmsTemplatesPage', icon: 'MessageSquarePlus', type: 'menu', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2271, parentId: 2270, title: '查询', type: 'button', permission: 'system:sms-template:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2272, parentId: 2270, title: '新增模板', type: 'button', permission: 'system:sms-template:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2273, parentId: 2270, title: '编辑模板', type: 'button', permission: 'system:sms-template:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2274, parentId: 2270, title: '删除模板', type: 'button', permission: 'system:sms-template:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2280, parentId: 2250, title: '短信发送记录', name: 'NotificationSmsSendLogs', path: '/system/sms-send-logs', component: 'system/sms-send-logs/SmsSendLogsPage', icon: 'MessageSquareX', type: 'menu', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2281, parentId: 2280, title: '查询', type: 'button', permission: 'system:sms-send-log:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2282, parentId: 2280, title: '测试发送', type: 'button', permission: 'system:sms-send-log:test', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2283, parentId: 2280, title: '删除记录', type: 'button', permission: 'system:sms-send-log:delete', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2284, parentId: 2280, title: '导出记录', type: 'button', permission: 'system:sms-send-log:export', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2290, parentId: 2200, title: '站内信管理', name: 'NotificationInApp', icon: 'Inbox', type: 'directory', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2300, parentId: 2290, title: '站内信模板', name: 'NotificationInAppTemplates', path: '/system/in-app-templates', component: 'system/in-app-templates/InAppTemplatesPage', icon: 'Newspaper', type: 'menu', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2301, parentId: 2300, title: '查询', type: 'button', permission: 'system:in-app-template:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2302, parentId: 2300, title: '新增模板', type: 'button', permission: 'system:in-app-template:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2303, parentId: 2300, title: '编辑模板', type: 'button', permission: 'system:in-app-template:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2304, parentId: 2300, title: '删除模板', type: 'button', permission: 'system:in-app-template:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2310, parentId: 2290, title: '收件记录', name: 'NotificationInAppMessages', path: '/system/in-app-messages', component: 'system/in-app-messages/InAppMessagesPage', icon: 'MailOpen', type: 'menu', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2311, parentId: 2310, title: '查询', type: 'button', permission: 'system:in-app-message:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2312, parentId: 2310, title: '标记已读', type: 'button', permission: 'system:in-app-message:read', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2313, parentId: 2310, title: '删除记录', type: 'button', permission: 'system:in-app-message:delete', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2320, parentId: 2200, title: '频道管理', name: 'NotificationChannels', path: '/system/channels', component: 'system/channels/ChannelsPage', icon: 'Radio', type: 'menu', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2321, parentId: 2320, title: '查询', type: 'button', permission: 'channel:channel:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2322, parentId: 2320, title: '新建频道', type: 'button', permission: 'channel:channel:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2323, parentId: 2320, title: '编辑频道', type: 'button', permission: 'channel:channel:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2324, parentId: 2320, title: '删除频道', type: 'button', permission: 'channel:channel:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2325, parentId: 2320, title: '群发消息', type: 'button', permission: 'channel:message:publish', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2326, parentId: 2320, title: '菜单配置', type: 'button', permission: 'channel:menu:save', sort: 5, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2327, parentId: 2320, title: '自动回复', type: 'button', permission: 'channel:reply:list', sort: 6, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2328, parentId: 2320, title: '保存自动回复', type: 'button', permission: 'channel:reply:save', sort: 7, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2329, parentId: 2320, title: '删除自动回复', type: 'button', permission: 'channel:reply:delete', sort: 8, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2330, parentId: 2200, title: '客服工作台', name: 'ChannelCustomerService', path: '/system/channel-cs', component: 'system/channel-cs/ChannelCustomerServicePage', icon: 'Headset', type: 'menu', sort: 5, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2331, parentId: 2330, title: '查询', type: 'button', permission: 'channel:cs', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2340, parentId: 2200, title: '频道数据', name: 'ChannelDashboard', path: '/system/channel-dashboard', component: 'system/channel-dashboard/ChannelDashboardPage', icon: 'ChartColumn', type: 'menu', sort: 6, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2341, parentId: 2340, title: '查询', type: 'button', permission: 'channel:dashboard', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2650, parentId: 2200, title: '通知策略', name: 'NotificationPolicies', path: '/system/notify-policies', component: 'system/notify-policies/NotifyPoliciesPage', icon: 'SlidersHorizontal', type: 'menu', sort: 7, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2651, parentId: 2650, title: '查询', type: 'button', permission: 'system:notify-policy:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2652, parentId: 2650, title: '保存策略', type: 'button', permission: 'system:notify-policy:save', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2653, parentId: 2650, title: '测试触发', type: 'button', permission: 'system:notify-policy:test', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },

  // ─── App 推送管理（2680 段,通知管理下）
  { id: 2680, parentId: 2200, title: 'App 推送', name: 'NotificationPush', icon: 'TabletSmartphone', type: 'directory', sort: 8, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2690, parentId: 2680, title: '推送配置', name: 'NotificationPushConfigs', path: '/system/push-configs', component: 'system/push-configs/PushConfigsPage', icon: 'Cog', type: 'menu', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2691, parentId: 2690, title: '查询', type: 'button', permission: 'system:push:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2692, parentId: 2690, title: '新增配置', type: 'button', permission: 'system:push:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2693, parentId: 2690, title: '编辑配置', type: 'button', permission: 'system:push:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2694, parentId: 2690, title: '删除配置', type: 'button', permission: 'system:push:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2695, parentId: 2690, title: '测试发送', type: 'button', permission: 'system:push:send', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2700, parentId: 2680, title: '推送记录', name: 'NotificationPushSendLogs', path: '/system/push-send-logs', component: 'system/push-send-logs/PushSendLogsPage', icon: 'ScrollText', type: 'menu', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2701, parentId: 2700, title: '查询', type: 'button', permission: 'system:push-log:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },

  // ─── 运营群发（2710 段,通知管理下）
  { id: 2710, parentId: 2200, title: '运营群发', name: 'NotificationBroadcasts', path: '/system/broadcasts', component: 'system/broadcasts/BroadcastsPage', icon: 'Megaphone', type: 'menu', sort: 9, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2711, parentId: 2710, title: '查询', type: 'button', permission: 'system:broadcast:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2712, parentId: 2710, title: '新建活动', type: 'button', permission: 'system:broadcast:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2713, parentId: 2710, title: '编辑活动', type: 'button', permission: 'system:broadcast:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2714, parentId: 2710, title: '删除活动', type: 'button', permission: 'system:broadcast:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2715, parentId: 2710, title: '发送', type: 'button', permission: 'system:broadcast:send', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2350, parentId: 2000, title: '标签管理', name: 'SystemTags', path: '/system/tags', component: 'system/tags/TagsPage', icon: 'Tags', type: 'menu', sort: 14, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2351, parentId: 2350, title: '查询', type: 'button', permission: 'system:tag:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2352, parentId: 2350, title: '新增标签', type: 'button', permission: 'system:tag:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2353, parentId: 2350, title: '编辑标签', type: 'button', permission: 'system:tag:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2354, parentId: 2350, title: '删除标签', type: 'button', permission: 'system:tag:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2360, parentId: 2000, title: '接口限流', name: 'SystemRateLimit', path: '/system/rate-limit', component: 'system/rate-limit/RateLimitPage', icon: 'Gauge', type: 'menu', sort: 15, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2361, parentId: 2360, title: '查询', type: 'button', permission: 'system:rate-limit:view', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2362, parentId: 2360, title: '编辑规则', type: 'button', permission: 'system:rate-limit:manage', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2363, parentId: 2360, title: '解封/重置', type: 'button', permission: 'system:rate-limit:manage', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2370, parentId: 2000, title: '数据库管理', name: 'SystemDbAdmin', path: '/system/db-admin', component: 'system/db-admin/DbAdminPage', icon: 'Database', type: 'menu', sort: 16, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2371, parentId: 2370, title: '查询', type: 'button', permission: 'system:db-admin:view', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2372, parentId: 2370, title: '执行 SQL', type: 'button', permission: 'system:db-admin:query', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2373, parentId: 2370, title: '导出结果', type: 'button', permission: 'system:db-admin:export', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2374, parentId: 2370, title: '修改数据', type: 'button', permission: 'system:db-admin:write', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2375, parentId: 2370, title: '运维操作', type: 'button', permission: 'system:db-admin:maintain', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2376, parentId: 2370, title: '数据库终端', type: 'button', permission: 'system:db-admin:terminal', sort: 5, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2380, parentId: 2000, title: 'Webhook 机器人', name: 'SystemChatBots', path: '/system/chat-bots', component: 'system/chat-bots/ChatBotsPage', icon: 'Bot', type: 'menu', sort: 16, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2381, parentId: 2380, title: '查询', type: 'button', permission: 'chat:bot:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2382, parentId: 2380, title: '新增机器人', type: 'button', permission: 'chat:bot:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2383, parentId: 2380, title: '编辑机器人', type: 'button', permission: 'chat:bot:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2384, parentId: 2380, title: '删除机器人', type: 'button', permission: 'chat:bot:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2390, parentId: 2000, title: '数据脱敏', name: 'SystemDataMask', path: '/system/data-mask', component: 'system/data-mask/DataMaskPage', icon: 'EyeOff', type: 'menu', sort: 17, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2391, parentId: 2390, title: '查询', type: 'button', permission: 'system:data-mask:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2392, parentId: 2390, title: '新增规则', type: 'button', permission: 'system:data-mask:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2393, parentId: 2390, title: '编辑规则', type: 'button', permission: 'system:data-mask:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2394, parentId: 2390, title: '删除规则', type: 'button', permission: 'system:data-mask:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2400, parentId: 2000, title: '系统调度', name: 'SystemScheduler', path: '/system/scheduler', component: 'system/scheduler/SystemSchedulerPage', icon: 'Timer', type: 'menu', sort: 18, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2401, parentId: 2400, title: '查询', type: 'button', permission: 'system:scheduler:view', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2402, parentId: 2400, title: '手动执行', type: 'button', permission: 'system:scheduler:run', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2403, parentId: 2400, title: '调整策略', type: 'button', permission: 'system:scheduler:config', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2404, parentId: 2400, title: '清理日志', type: 'button', permission: 'system:scheduler:cleanup', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2405, parentId: 2400, title: '确认告警', type: 'button', permission: 'system:scheduler:alert', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2410, parentId: 2000, title: '维护模式', name: 'SystemMaintenance', path: '/system/maintenance', component: 'system/maintenance/MaintenancePage', icon: 'Wrench', type: 'menu', sort: 19, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2411, parentId: 2410, title: '开启/关闭', type: 'button', permission: 'system:maintenance:manage', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2420, parentId: 2000, title: '导出中心', name: 'SystemExportJobs', path: '/system/export-jobs', component: 'system/export-jobs/ExportJobsPage', icon: 'Download', type: 'menu', sort: 19, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2421, parentId: 2420, title: '查询', type: 'button', permission: 'system:export-job:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2422, parentId: 2420, title: '下载文件', type: 'button', permission: 'system:export-job:download', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2423, parentId: 2420, title: '管理全部', type: 'button', permission: 'system:export-job:manage', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2424, parentId: 2420, title: '管理租户', type: 'button', permission: 'system:export-job:tenant-manage', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2425, parentId: 2420, title: '删除任务', type: 'button', permission: 'system:export-job:delete', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2430, parentId: 2000, title: '任务中心', name: 'SystemTaskCenter', path: '/system/task-center', component: 'system/task-center/TaskCenterPage', icon: 'ListChecks', type: 'menu', sort: 19, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2431, parentId: 2430, title: '查询', type: 'button', permission: 'system:async-task:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2432, parentId: 2430, title: '管理任务', type: 'button', permission: 'system:async-task:manage', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2433, parentId: 2430, title: '清理任务', type: 'button', permission: 'system:async-task:cleanup', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2434, parentId: 2430, title: '调整策略', type: 'button', permission: 'system:async-task:config', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2600, parentId: 2000, title: '数据保留', name: 'SystemRetention', path: '/system/retention', component: 'system/retention/RetentionPage', icon: 'Archive', type: 'menu', sort: 19, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2601, parentId: 2600, title: '查询', type: 'button', permission: 'system:retention:view', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2602, parentId: 2600, title: '编辑策略', type: 'button', permission: 'system:retention:edit', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2603, parentId: 2600, title: '立即清理', type: 'button', permission: 'system:retention:run', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2440, parentId: 2000, title: '系统运维', name: 'SystemOps', icon: 'Terminal', type: 'directory', sort: 20, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  // 运维概览用 2595/2596:段内 10 倍数槽位已满,2550/2560 是告警中心迁出时的保留位(permission-audit 测试封禁复用)
  { id: 2595, parentId: 2440, title: '运维概览', name: 'SystemOpsOverview', path: '/system/ops-overview', component: 'system/ops-overview/OpsOverviewPage', icon: 'LayoutDashboard', type: 'menu', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2596, parentId: 2595, title: '查询', type: 'button', permission: 'system:ops:overview', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  // 主机管理用 2597 + 按钮 2598/2599/2604(段内 10 倍数槽位与 2600-2603 已占用)
  { id: 2597, parentId: 2440, title: '主机管理', name: 'SystemOpsHosts', path: '/system/hosts', component: 'system/hosts/HostsPage', icon: 'Server', type: 'menu', sort: 14, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2598, parentId: 2597, title: '查询', type: 'button', permission: 'system:host:view', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2599, parentId: 2597, title: '管理主机', type: 'button', permission: 'system:host:manage', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2604, parentId: 2597, title: '远程操作', type: 'button', permission: 'system:host:use', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2450, parentId: 2440, title: 'Web 终端', name: 'SystemTerminal', path: '/system/terminal', component: 'system/terminal/TerminalPage', icon: 'TerminalSquare', type: 'menu', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2451, parentId: 2450, title: '执行终端', type: 'button', permission: 'system:terminal:execute', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2540, parentId: 2440, title: '终端会话', name: 'SystemTerminalSessions', path: '/system/terminal/sessions', component: 'system/terminal/TerminalSessionsPage', icon: 'Monitor', type: 'menu', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2541, parentId: 2540, title: '强制终止', type: 'button', permission: 'system:terminal:monitor', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2460, parentId: 2440, title: '终端录屏', name: 'TerminalRecordings', path: '/system/terminal/recordings', component: 'system/terminal/TerminalRecordingsPage', icon: 'Video', type: 'menu', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2461, parentId: 2460, title: '查询', type: 'button', permission: 'system:terminal:execute', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2470, parentId: 2440, title: '文件管理器', name: 'SystemFileManager', path: '/system/file-manager', component: 'system/file-manager/FileManagerPage', icon: 'HardDrive', type: 'menu', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2471, parentId: 2470, title: '查询', type: 'button', permission: 'system:file:use', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2480, parentId: 2440, title: '进程管理', name: 'SystemProcesses', path: '/system/processes', component: 'system/processes/ProcessesPage', icon: 'Cpu', type: 'menu', sort: 5, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2481, parentId: 2480, title: '查询', type: 'button', permission: 'system:process:view', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2482, parentId: 2480, title: '结束进程', type: 'button', permission: 'system:process:kill', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2483, parentId: 2480, title: '调整优先级', type: 'button', permission: 'system:process:priority', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2490, parentId: 2440, title: '端口监听', name: 'SystemPorts', path: '/system/ports', component: 'system/ports/PortsPage', icon: 'Network', type: 'menu', sort: 6, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2491, parentId: 2490, title: '查询', type: 'button', permission: 'system:port:view', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2492, parentId: 2490, title: '结束占用进程', type: 'button', permission: 'system:process:kill', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2500, parentId: 2440, title: 'Docker', name: 'SystemDocker', path: '/system/docker', component: 'system/docker/DockerPage', icon: 'Container', type: 'menu', sort: 7, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2501, parentId: 2500, title: '查询', type: 'button', permission: 'system:docker:view', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2502, parentId: 2500, title: '管理', type: 'button', permission: 'system:docker:manage', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2520, parentId: 2440, title: '服务管理', name: 'SystemServices', path: '/system/services', component: 'system/services/ServicesPage', icon: 'Settings', type: 'menu', sort: 8, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2521, parentId: 2520, title: '查询', type: 'button', permission: 'system:service:view', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2522, parentId: 2520, title: '管理', type: 'button', permission: 'system:service:manage', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2530, parentId: 2440, title: '日志查看器', name: 'SystemLogViewer', path: '/system/log-viewer', component: 'system/log-viewer/LogViewerPage', icon: 'FileText', type: 'menu', sort: 9, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2531, parentId: 2530, title: '查询', type: 'button', permission: 'system:log:view', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2510, parentId: 2440, title: '网络诊断', name: 'SystemNetworkDiag', path: '/system/network-diag', component: 'system/network-diag/NetworkDiagPage', icon: 'Wifi', type: 'menu', sort: 10, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2511, parentId: 2510, title: '执行诊断', type: 'button', permission: 'system:network:diag', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2570, parentId: 2440, title: '防火墙管理', name: 'SystemFirewall', path: '/system/firewall', component: 'system/firewall/FirewallPage', icon: 'Shield', type: 'menu', sort: 11, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2571, parentId: 2570, title: '查询', type: 'button', permission: 'system:firewall:view', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2572, parentId: 2570, title: '管理规则', type: 'button', permission: 'system:firewall:manage', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2580, parentId: 2440, title: 'Nginx 站点', name: 'SystemNginxSites', path: '/system/nginx-sites', component: 'system/nginx-sites/NginxSitesPage', icon: 'Globe', type: 'menu', sort: 12, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2581, parentId: 2580, title: '查询', type: 'button', permission: 'system:nginx:view', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2582, parentId: 2580, title: '管理站点', type: 'button', permission: 'system:nginx:manage', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2583, parentId: 2580, title: '重载 Nginx', type: 'button', permission: 'system:nginx:reload', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2590, parentId: 2440, title: 'SSL 证书', name: 'SystemSslCertificates', path: '/system/ssl-certificates', component: 'system/ssl-certificates/SslCertificatesPage', icon: 'Lock', type: 'menu', sort: 13, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2591, parentId: 2590, title: '查询', type: 'button', permission: 'system:ssl:view', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2592, parentId: 2590, title: '新增证书', type: 'button', permission: 'system:ssl:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2593, parentId: 2590, title: '删除证书', type: 'button', permission: 'system:ssl:delete', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },

  // ─── 应用版本管理（2670 段，客户端在线升级）
  { id: 2670, parentId: 2000, title: '应用版本', name: 'SystemAppReleases', path: '/system/app-releases', component: 'system/app-releases/AppReleasesPage', icon: 'Rocket', type: 'menu', sort: 14, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2671, parentId: 2670, title: '查询', type: 'button', permission: 'system:app-release:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2672, parentId: 2670, title: '新增版本', type: 'button', permission: 'system:app-release:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2673, parentId: 2670, title: '编辑版本', type: 'button', permission: 'system:app-release:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2674, parentId: 2670, title: '删除版本', type: 'button', permission: 'system:app-release:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2675, parentId: 2670, title: '发布/撤回', type: 'button', permission: 'system:app-release:publish', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },

  // ─── 智能助手（3000 段）
];
