import type { Menu } from '../../identity/contracts';
import { SEED_DATE } from '../_base';

/** 系统设置（2000 段） */
export const SEED_MENUS_SETTINGS: Menu[] = [
  { id: 2000, parentId: 0, title: '系统设置', name: 'SystemSettings', icon: 'Settings2', type: 'directory', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2010, parentId: 2000, title: '系统设置', name: 'SystemSettingsCenter', path: '/system/settings', component: 'system/settings/SettingsPage', icon: 'SlidersHorizontal', type: 'menu', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2020, parentId: 2000, title: '身份安全', name: 'SystemIdentitySecurity', path: '/system/identity-security', component: 'system/identity-security/IdentitySecurityPage', icon: 'Fingerprint', type: 'menu', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2030, parentId: 2000, title: '企业身份源', name: 'SystemIdentityProviders', path: '/system/identity-providers', component: 'system/identity-providers/IdentityProvidersPage', icon: 'Building2', type: 'menu', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },

  // ─── 通讯录同步（2610-2643）────────────────────────────────────────────────
  { id: 2610, parentId: 2000, title: '通讯录同步', name: 'SystemDirectorySync', icon: 'FolderSync', type: 'directory', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2620, parentId: 2610, title: '同步源配置', name: 'DirectorySyncSources', path: '/system/directory-sync/sources', component: 'system/directory-sync/DirectorySyncSourcesPage', icon: 'PlugZap', type: 'menu', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2630, parentId: 2610, title: '同步记录', name: 'DirectorySyncLogs', path: '/system/directory-sync/logs', component: 'system/directory-sync/DirectorySyncLogsPage', icon: 'History', type: 'menu', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2640, parentId: 2610, title: '冲突处理', name: 'DirectorySyncConflicts', path: '/system/directory-sync/conflicts', component: 'system/directory-sync/DirectorySyncConflictsPage', icon: 'GitMerge', type: 'menu', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2040, parentId: 2000, title: '文件管理', name: 'SystemFiles', icon: 'FolderOpen', type: 'directory', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2050, parentId: 2040, title: '文件配置', name: 'SystemFileConfigs', path: '/system/file-configs', component: 'system/file-configs/FileStorageConfigsPage', icon: 'HardDriveUpload', type: 'menu', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2060, parentId: 2040, title: '文件列表', name: 'SystemFileList', path: '/system/files', component: 'system/files/FilesPage', icon: 'Files', type: 'menu', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2070, parentId: 2000, title: 'OAuth配置', name: 'SystemOAuthConfig', path: '/system/oauth-config', component: 'system/oauth-config/OAuthConfigPage', icon: 'KeyRound', type: 'menu', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  // 系统监控：本系统自身的运行状态与可观测性数据（服务监控 / 链路追踪 / 日志文件 / 异常日志），
  // 与「审计日志」（谁在什么时候做了什么）和「系统运维」（主机级工具箱）分开
  { id: 2750, parentId: 2000, title: '系统监控', name: 'SystemMonitoring', icon: 'Activity', type: 'directory', sort: 5, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2080, parentId: 2750, title: '服务监控', name: 'SystemMonitor', path: '/system/monitor', component: 'system/monitor/MonitorPage', icon: 'Gauge', type: 'menu', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2790, parentId: 2750, title: 'WebSocket 连接', name: 'SystemWebSocketMonitor', path: '/system/monitor/websocket', component: 'system/monitor/WebSocketMonitorPage', icon: 'RadioTower', type: 'menu', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2780, parentId: 2750, title: 'SQL 监控', name: 'SystemSqlMonitor', path: '/system/sql-monitor', component: 'system/sql-monitor/SqlMonitorPage', icon: 'ChartNoAxesCombined', type: 'menu', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2760, parentId: 2750, title: '异常日志', name: 'SystemExceptionLogs', path: '/system/exception-logs', component: 'system/exception-logs/ExceptionLogsPage', icon: 'Bug', type: 'menu', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2720, parentId: 2750, title: '链路追踪', name: 'SystemTrace', path: '/system/trace', component: 'system/trace/TracePage', icon: 'Route', type: 'menu', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2150, parentId: 2750, title: '日志文件', name: 'SystemLogFiles', path: '/system/log-files', component: 'system/log-files/LogFilesPage', icon: 'FileText', type: 'menu', sort: 5, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2090, parentId: 2000, title: '在线用户', name: 'SystemSessions', path: '/system/sessions', component: 'system/sessions/OnlineSessionsPage', icon: 'MonitorSmartphone', type: 'menu', sort: 6, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2100, parentId: 2000, title: '定时任务', name: 'SystemCronJobs', path: '/system/cron-jobs', component: 'system/cron-jobs/CronJobsPage', icon: 'Clock', type: 'menu', sort: 7, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  // 审计日志：谁在什么时候做了什么（登录 / 操作 / 模拟登录）
  { id: 2120, parentId: 2000, title: '审计日志', name: 'SystemAuditLogs', icon: 'ClipboardMinus', type: 'directory', sort: 9, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2130, parentId: 2120, title: '登录日志', name: 'SystemLoginLogs', path: '/system/login-logs', component: 'system/login-logs/LoginLogsPage', icon: 'List', type: 'menu', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2140, parentId: 2120, title: '操作日志', name: 'SystemOperationLogs', path: '/system/operation-logs', component: 'system/operation-logs/OperationLogsPage', icon: 'ClipboardList', type: 'menu', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2740, parentId: 2120, title: '模拟登录记录', name: 'SystemImpersonationRecords', path: '/system/impersonation-records', component: 'system/impersonation/ImpersonationRecordsPage', icon: 'VenetianMask', type: 'menu', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2730, parentId: 2000, title: '导入中心', name: 'SystemImportCenter', path: '/system/import-center', component: 'system/import-center/ImportCenterPage', icon: 'Upload', type: 'menu', sort: 19, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2160, parentId: 2000, title: '公告管理', name: 'SystemAnnouncements', path: '/system/announcements', component: 'system/announcements/AnnouncementsPage', icon: 'Megaphone', type: 'menu', sort: 10, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2170, parentId: 2000, title: 'IP访问控制', name: 'SystemIpAccess', path: '/system/ip-access', component: 'system/ip-access/IpAccessPage', icon: 'ShieldBan', type: 'menu', sort: 11, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2180, parentId: 2000, title: '意见反馈', name: 'SystemFeedbacks', path: '/system/feedbacks', component: 'system/feedbacks/FeedbacksPage', icon: 'MessageSquareHeart', type: 'menu', sort: 11, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2190, parentId: 2000, title: '缓存管理', name: 'SystemCache', path: '/system/cache', component: 'system/cache/CacheManagePage', icon: 'BrainCircuit', type: 'menu', sort: 12, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2200, parentId: 2000, title: '通知管理', name: 'SystemNotification', icon: 'BellRing', type: 'directory', sort: 13, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2210, parentId: 2200, title: '邮件管理', name: 'NotificationEmail', icon: 'Mail', type: 'directory', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2220, parentId: 2210, title: '邮件配置', name: 'NotificationEmailConfig', path: '/system/email-config', component: 'system/email-config/EmailConfigPage', icon: 'MailCheck', type: 'menu', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2230, parentId: 2210, title: '邮件模板', name: 'NotificationEmailTemplates', path: '/system/email-templates', component: 'system/email-templates/EmailTemplatesPage', icon: 'MailPlus', type: 'menu', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2240, parentId: 2210, title: '邮件发送记录', name: 'NotificationEmailSendLogs', path: '/system/email-send-logs', component: 'system/email-send-logs/EmailSendLogsPage', icon: 'MailX', type: 'menu', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2250, parentId: 2200, title: '短信管理', name: 'NotificationSms', icon: 'MessageSquareText', type: 'directory', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2260, parentId: 2250, title: '短信配置', name: 'NotificationSmsConfigs', path: '/system/sms-configs', component: 'system/sms-configs/SmsConfigsPage', icon: 'Smartphone', type: 'menu', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2270, parentId: 2250, title: '短信模板', name: 'NotificationSmsTemplates', path: '/system/sms-templates', component: 'system/sms-templates/SmsTemplatesPage', icon: 'MessageSquarePlus', type: 'menu', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2280, parentId: 2250, title: '短信发送记录', name: 'NotificationSmsSendLogs', path: '/system/sms-send-logs', component: 'system/sms-send-logs/SmsSendLogsPage', icon: 'MessageSquareX', type: 'menu', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2290, parentId: 2200, title: '站内信管理', name: 'NotificationInApp', icon: 'Inbox', type: 'directory', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2300, parentId: 2290, title: '站内信模板', name: 'NotificationInAppTemplates', path: '/system/in-app-templates', component: 'system/in-app-templates/InAppTemplatesPage', icon: 'Newspaper', type: 'menu', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2310, parentId: 2290, title: '收件记录', name: 'NotificationInAppMessages', path: '/system/in-app-messages', component: 'system/in-app-messages/InAppMessagesPage', icon: 'MailOpen', type: 'menu', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2320, parentId: 2200, title: '频道管理', name: 'NotificationChannels', path: '/system/channels', component: 'system/channels/ChannelsPage', icon: 'Radio', type: 'menu', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2330, parentId: 2200, title: '客服工作台', name: 'ChannelCustomerService', path: '/system/channel-cs', component: 'system/channel-cs/ChannelCustomerServicePage', icon: 'Headset', type: 'menu', sort: 5, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2340, parentId: 2200, title: '频道数据', name: 'ChannelDashboard', path: '/system/channel-dashboard', component: 'system/channel-dashboard/ChannelDashboardPage', icon: 'ChartColumn', type: 'menu', sort: 6, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2650, parentId: 2200, title: '通知策略', name: 'NotificationPolicies', path: '/system/notify-policies', component: 'system/notify-policies/NotifyPoliciesPage', icon: 'SlidersHorizontal', type: 'menu', sort: 7, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },

  // ─── App 推送管理（2680 段,通知管理下）
  { id: 2680, parentId: 2200, title: 'App 推送', name: 'NotificationPush', icon: 'TabletSmartphone', type: 'directory', sort: 8, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2690, parentId: 2680, title: '推送配置', name: 'NotificationPushConfigs', path: '/system/push-configs', component: 'system/push-configs/PushConfigsPage', icon: 'Cog', type: 'menu', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2700, parentId: 2680, title: '推送记录', name: 'NotificationPushSendLogs', path: '/system/push-send-logs', component: 'system/push-send-logs/PushSendLogsPage', icon: 'ScrollText', type: 'menu', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },

  // ─── 运营群发（2710 段,通知管理下）
  { id: 2710, parentId: 2200, title: '运营群发', name: 'NotificationBroadcasts', path: '/system/broadcasts', component: 'system/broadcasts/BroadcastsPage', icon: 'Megaphone', type: 'menu', sort: 9, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2350, parentId: 2000, title: '标签管理', name: 'SystemTags', path: '/system/tags', component: 'system/tags/TagsPage', icon: 'Tags', type: 'menu', sort: 14, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2360, parentId: 2000, title: '接口限流', name: 'SystemRateLimit', path: '/system/rate-limit', component: 'system/rate-limit/RateLimitPage', icon: 'Gauge', type: 'menu', sort: 15, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2370, parentId: 2000, title: '数据库管理', name: 'SystemDbAdmin', path: '/system/db-admin', component: 'system/db-admin/DbAdminPage', icon: 'Database', type: 'menu', sort: 16, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2380, parentId: 2000, title: 'Webhook 机器人', name: 'SystemChatBots', path: '/system/chat-bots', component: 'system/chat-bots/ChatBotsPage', icon: 'Bot', type: 'menu', sort: 16, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2390, parentId: 2000, title: '数据脱敏', name: 'SystemDataMask', path: '/system/data-mask', component: 'system/data-mask/DataMaskPage', icon: 'EyeOff', type: 'menu', sort: 17, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2400, parentId: 2000, title: '系统调度', name: 'SystemScheduler', path: '/system/scheduler', component: 'system/scheduler/SystemSchedulerPage', icon: 'Timer', type: 'menu', sort: 18, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2410, parentId: 2000, title: '维护模式', name: 'SystemMaintenance', path: '/system/maintenance', component: 'system/maintenance/MaintenancePage', icon: 'Wrench', type: 'menu', sort: 19, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2420, parentId: 2000, title: '导出中心', name: 'SystemExportJobs', path: '/system/export-jobs', component: 'system/export-jobs/ExportJobsPage', icon: 'Download', type: 'menu', sort: 19, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2430, parentId: 2000, title: '任务中心', name: 'SystemTaskCenter', path: '/system/task-center', component: 'system/task-center/TaskCenterPage', icon: 'ListChecks', type: 'menu', sort: 19, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2600, parentId: 2000, title: '数据保留', name: 'SystemRetention', path: '/system/retention', component: 'system/retention/RetentionPage', icon: 'Archive', type: 'menu', sort: 19, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2440, parentId: 2000, title: '系统运维', name: 'SystemOps', icon: 'Terminal', type: 'directory', sort: 20, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  // 运维概览用 2595/2596:段内 10 倍数槽位已满,2550/2560 是告警中心迁出时的保留位(permission-audit 测试封禁复用)
  { id: 2595, parentId: 2440, title: '运维概览', name: 'SystemOpsOverview', path: '/system/ops-overview', component: 'system/ops-overview/OpsOverviewPage', icon: 'LayoutDashboard', type: 'menu', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  // 主机管理用 2597 + 按钮 2598/2599/2604(段内 10 倍数槽位与 2600-2603 已占用)
  { id: 2597, parentId: 2440, title: '主机管理', name: 'SystemOpsHosts', path: '/system/hosts', component: 'system/hosts/HostsPage', icon: 'Server', type: 'menu', sort: 14, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2450, parentId: 2440, title: 'Web 终端', name: 'SystemTerminal', path: '/system/terminal', component: 'system/terminal/TerminalPage', icon: 'TerminalSquare', type: 'menu', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2540, parentId: 2440, title: '终端会话', name: 'SystemTerminalSessions', path: '/system/terminal/sessions', component: 'system/terminal/TerminalSessionsPage', icon: 'Monitor', type: 'menu', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2460, parentId: 2440, title: '终端录屏', name: 'TerminalRecordings', path: '/system/terminal/recordings', component: 'system/terminal/TerminalRecordingsPage', icon: 'Video', type: 'menu', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2470, parentId: 2440, title: '文件管理器', name: 'SystemFileManager', path: '/system/file-manager', component: 'system/file-manager/FileManagerPage', icon: 'HardDrive', type: 'menu', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2480, parentId: 2440, title: '进程管理', name: 'SystemProcesses', path: '/system/processes', component: 'system/processes/ProcessesPage', icon: 'Cpu', type: 'menu', sort: 5, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2490, parentId: 2440, title: '端口监听', name: 'SystemPorts', path: '/system/ports', component: 'system/ports/PortsPage', icon: 'Network', type: 'menu', sort: 6, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2500, parentId: 2440, title: 'Docker', name: 'SystemDocker', path: '/system/docker', component: 'system/docker/DockerPage', icon: 'Container', type: 'menu', sort: 7, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2520, parentId: 2440, title: '服务管理', name: 'SystemServices', path: '/system/services', component: 'system/services/ServicesPage', icon: 'Settings', type: 'menu', sort: 8, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2530, parentId: 2440, title: '日志查看器', name: 'SystemLogViewer', path: '/system/log-viewer', component: 'system/log-viewer/LogViewerPage', icon: 'FileText', type: 'menu', sort: 9, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2510, parentId: 2440, title: '网络诊断', name: 'SystemNetworkDiag', path: '/system/network-diag', component: 'system/network-diag/NetworkDiagPage', icon: 'Wifi', type: 'menu', sort: 10, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2570, parentId: 2440, title: '防火墙管理', name: 'SystemFirewall', path: '/system/firewall', component: 'system/firewall/FirewallPage', icon: 'Shield', type: 'menu', sort: 11, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2580, parentId: 2440, title: 'Nginx 站点', name: 'SystemNginxSites', path: '/system/nginx-sites', component: 'system/nginx-sites/NginxSitesPage', icon: 'Globe', type: 'menu', sort: 12, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2590, parentId: 2440, title: 'SSL 证书', name: 'SystemSslCertificates', path: '/system/ssl-certificates', component: 'system/ssl-certificates/SslCertificatesPage', icon: 'Lock', type: 'menu', sort: 13, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  // ─── 应用交付（同在系统运维目录：应用版本 = 应用 / 版本 / 制品；应用部署 = 目标 / 记录 / 备份，两页深链互跳）
  { id: 2670, parentId: 2440, title: '应用版本', name: 'SystemAppReleases', path: '/system/app-releases', component: 'system/app-releases/AppReleasesPage', icon: 'Rocket', type: 'menu', sort: 15, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2770, parentId: 2440, title: '应用部署', name: 'SystemDeploy', path: '/system/deploy', component: 'system/deploy/DeployPage', icon: 'CloudUpload', type: 'menu', sort: 16, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },

  // ─── 智能助手（3000 段）
];
