import type { Menu } from '../../identity/contracts';
import { SEED_DATE } from '../_base';

/** 工作流引擎（4000 段）— 按角色分三组:审批中心(4200)/流程管理(4300)/运维与集成(4400) */
export const SEED_MENUS_WORKFLOW: Menu[] = [
  { id: 4000, parentId: 0, title: '工作流引擎', name: 'Workflow', icon: 'GitFork', type: 'directory', sort: 6, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },

  // ─── 审批中心（全员日常）───────────────────────────────────────────────
  { id: 4200, parentId: 4000, title: '审批中心', name: 'WorkflowApprovalCenter', icon: 'Inbox', type: 'directory', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4010, parentId: 4200, title: '发起工作台', name: 'WorkflowLaunchpad', path: '/workflow/launchpad', component: 'workflow/launchpad/WorkflowLaunchpadPage', icon: 'LayoutGrid', type: 'menu', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4011, parentId: 4010, title: '查询', type: 'button', permission: 'workflow:instance:create', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4080, parentId: 4200, title: '待我审批', name: 'PendingApprovals', path: '/workflow/pending', component: 'workflow/tasks/PendingApprovalsPage', icon: 'ClipboardCheck', type: 'menu', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4081, parentId: 4080, title: '查询', type: 'button', permission: 'workflow:task:handle', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4082, parentId: 4080, title: '打印审批单', type: 'button', permission: 'workflow:instance:print', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4070, parentId: 4200, title: '我的申请', name: 'MyApplications', path: '/workflow/applications', component: 'workflow/instances/MyApplicationsPage', icon: 'FilePlus2', type: 'menu', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4071, parentId: 4070, title: '查询', type: 'button', permission: 'workflow:instance:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4072, parentId: 4070, title: '发起申请', type: 'button', permission: 'workflow:instance:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4073, parentId: 4070, title: '打印审批单', type: 'button', permission: 'workflow:instance:print', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4090, parentId: 4200, title: '抄送我的', name: 'WorkflowCcToMe', path: '/workflow/cc', component: 'workflow/cc/CcToMePage', icon: 'Send', type: 'menu', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4091, parentId: 4090, title: '查询', type: 'button', permission: 'workflow:instance:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4100, parentId: 4200, title: '我已办', name: 'WorkflowHandled', path: '/workflow/handled', component: 'workflow/handled/HandledPage', icon: 'CircleCheckBig', type: 'menu', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4101, parentId: 4100, title: '查询', type: 'button', permission: 'workflow:task:handle', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4160, parentId: 4200, title: '审批代理', name: 'WorkflowDelegations', path: '/workflow/delegations', component: 'workflow/delegations/WorkflowDelegationsPage', icon: 'UserRoundCog', type: 'menu', sort: 5, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4161, parentId: 4160, title: '查询', type: 'button', permission: 'workflow:delegation:view', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4162, parentId: 4160, title: '管理审批代理', type: 'button', permission: 'workflow:delegation:manage', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },

  // ─── 流程管理（流程管理员）─────────────────────────────────────────────
  { id: 4300, parentId: 4000, title: '流程管理', name: 'WorkflowManagement', icon: 'PencilRuler', type: 'directory', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4020, parentId: 4300, title: '流程定义', name: 'WorkflowDefinitions', path: '/workflow/definitions', component: 'workflow/definitions/WorkflowDefinitionsPage', icon: 'Workflow', type: 'menu', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4021, parentId: 4020, title: '查询', type: 'button', permission: 'workflow:definition:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4022, parentId: 4020, title: '新建流程', type: 'button', permission: 'workflow:definition:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4023, parentId: 4020, title: '编辑流程', type: 'button', permission: 'workflow:definition:edit', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4024, parentId: 4020, title: '删除流程', type: 'button', permission: 'workflow:definition:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4025, parentId: 4020, title: '发布/禁用', type: 'button', permission: 'workflow:definition:publish', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4030, parentId: 4020, title: '流程设计', name: 'WorkflowDesigner', path: '/workflow/designer', component: 'workflow/designer/WorkflowDesignerPage', icon: 'PencilRuler', type: 'menu', sort: 5, status: 'enabled', visible: false, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4040, parentId: 4300, title: '流程模板', name: 'WorkflowTemplates', path: '/workflow/templates', component: 'workflow/templates/WorkflowTemplatesPage', icon: 'LayoutTemplate', type: 'menu', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4041, parentId: 4040, title: '查询', type: 'button', permission: 'workflow:definition:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4050, parentId: 4300, title: '表单库', name: 'WorkflowForms', path: '/workflow/forms', component: 'workflow/forms/WorkflowFormsPage', icon: 'LayoutList', type: 'menu', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4051, parentId: 4050, title: '查询', type: 'button', permission: 'workflow:form:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4052, parentId: 4050, title: '新建表单', type: 'button', permission: 'workflow:form:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4053, parentId: 4050, title: '编辑表单', type: 'button', permission: 'workflow:form:edit', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4054, parentId: 4050, title: '删除表单', type: 'button', permission: 'workflow:form:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4060, parentId: 4050, title: '表单设计', name: 'WorkflowFormDesigner', path: '/workflow/forms/designer', component: 'workflow/forms/WorkflowFormDesignerPage', icon: 'PencilRuler', type: 'menu', sort: 4, status: 'enabled', visible: false, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4140, parentId: 4300, title: '流程自动化', name: 'WorkflowAutomations', path: '/workflow/automations', component: 'workflow/automations/WorkflowAutomationsPage', icon: 'Bot', type: 'menu', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4141, parentId: 4140, title: '查询', type: 'button', permission: 'workflow:definition:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4142, parentId: 4140, title: '新建规则', type: 'button', permission: 'workflow:definition:edit', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4143, parentId: 4140, title: '编辑规则', type: 'button', permission: 'workflow:definition:edit', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4144, parentId: 4140, title: '删除规则', type: 'button', permission: 'workflow:definition:edit', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4170, parentId: 4300, title: '定时发起', name: 'WorkflowSchedules', path: '/workflow/schedules', component: 'workflow/schedules/WorkflowSchedulesPage', icon: 'CalendarClock', type: 'menu', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4171, parentId: 4170, title: '查询', type: 'button', permission: 'workflow:schedule:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4172, parentId: 4170, title: '新建定时', type: 'button', permission: 'workflow:schedule:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4173, parentId: 4170, title: '编辑定时', type: 'button', permission: 'workflow:schedule:edit', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4174, parentId: 4170, title: '删除定时', type: 'button', permission: 'workflow:schedule:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },

  // ─── 运维与集成（运维人员）─────────────────────────────────────────────
  { id: 4400, parentId: 4000, title: '运维与集成', name: 'WorkflowOps', icon: 'Activity', type: 'directory', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4110, parentId: 4400, title: '流程监控', name: 'WorkflowMonitor', path: '/workflow/monitor', component: 'workflow/monitor/WorkflowMonitorPage', icon: 'BarChart2', type: 'menu', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4111, parentId: 4110, title: '查询', type: 'button', permission: 'workflow:instance:monitor', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4112, parentId: 4110, title: '取消流程', type: 'button', permission: 'workflow:instance:cancel', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4113, parentId: 4110, title: '删除流程', type: 'button', permission: 'workflow:instance:delete', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4114, parentId: 4110, title: '引擎运维', type: 'button', permission: 'workflow:engine:operate', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4115, parentId: 4110, title: '离职交接', type: 'button', permission: 'workflow:task:handover', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4116, parentId: 4110, title: '打印审批单', type: 'button', permission: 'workflow:instance:print', sort: 5, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4150, parentId: 4400, title: '健康巡检', name: 'WorkflowHealth', path: '/workflow/health', component: 'workflow/health/WorkflowHealthPage', icon: 'Stethoscope', type: 'menu', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4151, parentId: 4150, title: '查询', type: 'button', permission: 'workflow:health:view', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4120, parentId: 4400, title: '事件订阅', name: 'WorkflowEventSubscriptions', path: '/workflow/event-subscriptions', component: 'workflow/event-subscriptions/WorkflowEventSubscriptionsPage', icon: 'Webhook', type: 'menu', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4121, parentId: 4120, title: '查询', type: 'button', permission: 'workflow:event-subscription:view', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4122, parentId: 4120, title: '新建订阅', type: 'button', permission: 'workflow:event-subscription:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4123, parentId: 4120, title: '编辑订阅', type: 'button', permission: 'workflow:event-subscription:edit', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4124, parentId: 4120, title: '删除订阅', type: 'button', permission: 'workflow:event-subscription:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4125, parentId: 4120, title: '投递记录', type: 'button', permission: 'workflow:event-delivery:view', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4126, parentId: 4120, title: '重试投递', type: 'button', permission: 'workflow:event-delivery:retry', sort: 5, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4130, parentId: 4400, title: '触发器执行', name: 'WorkflowTriggerExecutions', path: '/workflow/trigger-executions', component: 'workflow/trigger-executions/WorkflowTriggerExecutionsPage', icon: 'Zap', type: 'menu', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4131, parentId: 4130, title: '查询', type: 'button', permission: 'workflow:trigger-execution:view', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4180, parentId: 4400, title: '远程数据源', name: 'WorkflowDataSources', path: '/workflow/data-sources', component: 'workflow/data-sources/WorkflowDataSourcesPage', icon: 'DatabaseZap', type: 'menu', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4181, parentId: 4180, title: '查询', type: 'button', permission: 'workflow:datasource:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4182, parentId: 4180, title: '新增数据源', type: 'button', permission: 'workflow:datasource:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4183, parentId: 4180, title: '编辑数据源', type: 'button', permission: 'workflow:datasource:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4184, parentId: 4180, title: '删除数据源', type: 'button', permission: 'workflow:datasource:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4190, parentId: 4400, title: '连接器', name: 'WorkflowConnectors', path: '/workflow/connectors', component: 'workflow/connectors/WorkflowConnectorsPage', icon: 'Cable', type: 'menu', sort: 5, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4191, parentId: 4190, title: '查询', type: 'button', permission: 'workflow:connector:list', sort: 0, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4192, parentId: 4190, title: '新增连接器', type: 'button', permission: 'workflow:connector:create', sort: 1, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4193, parentId: 4190, title: '编辑连接器', type: 'button', permission: 'workflow:connector:update', sort: 2, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4194, parentId: 4190, title: '删除连接器', type: 'button', permission: 'workflow:connector:delete', sort: 3, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4195, parentId: 4190, title: '测试连接器', type: 'button', permission: 'workflow:connector:test', sort: 4, status: 'enabled', visible: true, createdAt: SEED_DATE, updatedAt: SEED_DATE },

  // ─── 消息中心（5000 段）
];
