import { definePermissions } from '../core/permissions';

/**
 * cms 域权限码注册表：code → 按钮标题 / 所属页面（菜单 name）。
 * 种子 button 节点由此生成（@zenith/shared/seed），契约操作 / 路由门禁 / 前端按钮以 `Permission` 类型引用。
 * `uiOnly` = 服务端没有任何接口检查该码（纯前端门控或待清理）。
 */
export const CMS_PERMISSIONS = definePermissions({
  'cms:dashboard:view': { label: '查询', menu: 'CmsDashboard' },
  'cms:site:list': { label: '查询', menu: ['CmsSites', 'CmsDashboard', 'CmsStats', 'CmsWorkspace'] },
  'cms:site:create': { label: '新增站点', menu: 'CmsSites' },
  'cms:site:update': { label: '编辑站点', menu: 'CmsSites' },
  'cms:site:delete': { label: '删除站点', menu: 'CmsSites' },
  'cms:publish:build': { label: '全站静态化', menu: 'CmsSites' },
  'cms:site:hierarchy': { label: '管理站群层级', menu: 'CmsSites' },
  'cms:publish:group': { label: '站群批量发布', menu: 'CmsSites' },
  'cms:channel:list': { label: '查询', menu: 'CmsChannels' },
  'cms:channel:create': { label: '新增栏目', menu: 'CmsChannels' },
  'cms:channel:update': { label: '编辑栏目', menu: 'CmsChannels' },
  'cms:channel:delete': { label: '删除栏目', menu: 'CmsChannels' },
  'cms:content:list': { label: '查询', menu: ['CmsContents', 'CmsContentEdit', 'CmsWorkspace'] },
  'cms:content:create': { label: '新增内容', menu: 'CmsContents' },
  'cms:content:update': { label: '编辑内容', menu: 'CmsContents' },
  'cms:content:delete': { label: '删除内容', menu: 'CmsContents' },
  'cms:content:publish': { label: '发布内容', menu: 'CmsContents' },
  'cms:content:audit': { label: '审核内容', menu: 'CmsContents' },
  'cms:content:lock': { label: '锁定内容', menu: 'CmsContents' },
  'cms:content:export': { label: '导出内容', menu: 'CmsContents' },
  'cms:resource:list': { label: '查询', menu: 'CmsResources' },
  'cms:resource:upload': { label: '上传素材', menu: 'CmsResources' },
  'cms:resource:update': { label: '编辑素材', menu: 'CmsResources' },
  'cms:resource:delete': { label: '删除素材', menu: 'CmsResources' },
  'cms:model:list': { label: '查询', menu: 'CmsModels' },
  'cms:model:create': { label: '新增模型', menu: 'CmsModels' },
  'cms:model:update': { label: '编辑模型', menu: 'CmsModels' },
  'cms:model:delete': { label: '删除模型', menu: 'CmsModels' },
  'cms:tag:list': { label: '查询', menu: 'CmsTags' },
  'cms:tag:create': { label: '新增标签', menu: 'CmsTags' },
  'cms:tag:update': { label: '编辑标签', menu: 'CmsTags' },
  'cms:tag:delete': { label: '删除标签', menu: 'CmsTags' },
  'cms:link:list': { label: '查询', menu: 'CmsFriendLinks' },
  'cms:link:create': { label: '新增友链', menu: 'CmsFriendLinks' },
  'cms:link:update': { label: '编辑友链', menu: 'CmsFriendLinks' },
  'cms:link:delete': { label: '删除友链', menu: 'CmsFriendLinks' },
  'cms:search:manage': { label: '查询', menu: 'CmsSearch' },
  'cms:seo:manage': { label: '查询', menu: 'CmsSeo' },
  'cms:seo:push': { label: '搜索引擎推送', menu: 'CmsSeo' },
  'cms:comment:list': { label: '查询', menu: 'CmsComments' },
  'cms:comment:audit': { label: '审核评论', menu: 'CmsComments' },
  'cms:comment:delete': { label: '删除评论', menu: 'CmsComments' },
  'cms:ad:list': { label: '查询', menu: 'CmsAds' },
  'cms:ad:manage': { label: '管理广告', menu: 'CmsAds' },
  'cms:ad-event:list': { label: '查看广告事件', menu: 'CmsAds' },
  'cms:ad-event:export': { label: '导出广告事件', menu: 'CmsAds' },
  'cms:ad-event:cleanup': { label: '清理广告事件', menu: 'CmsAds' },
  'cms:ad-event:export-raw': { label: '导出广告原始明细', menu: 'CmsAds' },
  'cms:form:list': { label: '查询', menu: ['CmsForms', 'CmsWorkspace'] },
  'cms:form:manage': { label: '管理表单', menu: 'CmsForms' },
  'cms:feedback:manage': { label: '办理读者反馈', menu: 'CmsForms' },
  'cms:editorial-task:manage': { label: '管理编辑事项', menu: 'CmsWorkspace' },
  'cms:sensitive:list': { label: '查询', menu: 'CmsSensitiveWords' },
  'cms:sensitive:manage': { label: '管理敏感词', menu: 'CmsSensitiveWords' },
  'cms:collect:list': { label: '查询', menu: 'CmsCollect' },
  'cms:collect:create': { label: '新增规则', menu: 'CmsCollect' },
  'cms:collect:update': { label: '编辑规则', menu: 'CmsCollect' },
  'cms:collect:delete': { label: '删除规则', menu: 'CmsCollect' },
  'cms:collect:run': { label: '执行采集', menu: 'CmsCollect' },
  'cms:widget:list': { label: '查询', menu: ['CmsWidgets', 'CmsWidgetEdit'] },
  'cms:widget:create': { label: '新增部件', menu: 'CmsWidgets' },
  'cms:widget:update': { label: '编辑部件', menu: 'CmsWidgets' },
  'cms:widget:publish': { label: '发布部件', menu: 'CmsWidgets' },
  'cms:widget:offline': { label: '下线部件', menu: 'CmsWidgets' },
  'cms:widget:delete': { label: '删除部件', menu: 'CmsWidgets' },
  'cms:widget:bind': { label: '绑定主题插槽', menu: 'CmsWidgets' },
  'cms:page:list': { label: '查询', menu: 'CmsPages' },
  'cms:page:create': { label: '新增页面', menu: 'CmsPages' },
  'cms:page:update': { label: '编辑页面', menu: 'CmsPages' },
  'cms:page:delete': { label: '删除页面', menu: 'CmsPages' },
  'cms:page:acl': { label: '管理区块权限', menu: 'CmsPages' },
  'cms:word:list': { label: '查询', menu: 'CmsErrorProneWords' },
  'cms:word:manage': { label: '管理易错词', menu: 'CmsErrorProneWords' },
  'cms:interaction:list': { label: '查询', menu: ['CmsInteractions', 'CmsInteractionEdit'] },
  'cms:interaction:manage': { label: '管理互动问卷', menu: 'CmsInteractions' },
  'cms:interaction:batch': { label: '批量流转互动', menu: 'CmsInteractions' },
  'cms:interaction:export': { label: '导出互动答卷', menu: 'CmsInteractions' },
  'cms:interaction:export-raw': { label: '导出互动原始答卷', menu: 'CmsInteractions' },
  'cms:stat:view': { label: '查询', menu: 'CmsStats' },
  'cms:publish:view': { label: '查询', menu: 'CmsPublishing' },
  'cms:publish:manage': { label: '管理发布任务', menu: 'CmsPublishing' },
  'cms:subscription:list': { label: '查询', menu: 'CmsSubscriptions' },
  'cms:subscription:export': { label: '导出订阅明细', menu: 'CmsSubscriptions' },
  'cms:subscription:export-raw': { label: '导出订阅原始明细', menu: 'CmsSubscriptions' },
  'cms:distribution:list': { label: '查询', menu: 'CmsDistribution' },
  'cms:distribution:create': { label: '新增分发规则', menu: 'CmsDistribution' },
  'cms:distribution:update': { label: '编辑分发规则', menu: 'CmsDistribution' },
  'cms:distribution:delete': { label: '删除分发规则', menu: 'CmsDistribution' },
  'cms:distribution:run': { label: '执行内容分发', menu: 'CmsDistribution' },
  'cms:distribution:export': { label: '导出分发结果', menu: 'CmsDistribution' },
});
