import type { CronJob, DataMaskConfig, Dict, DictItem, Tag, UserFeedback } from '../platform/contracts';
import type { MonitorAlertLevel, MonitorAlertOperator, MonitorMetric } from '../platform/constants';
import { SEED_DATE } from './_base';

// ─── 字典 ─────────────────────────────────────────────────────────────────────

export const SEED_DICTS: Dict[] = [
  { id: 1, name: '通用状态',     code: 'common_status',         description: '通用启用/禁用状态',  status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 3, name: '菜单类型',     code: 'menu_type',             description: '菜单节点类型',       status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4, name: '用户性别',     code: 'user_gender',           description: '用户性别',           status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 5, name: '显示状态',     code: 'menu_visible',          description: '菜单显示/隐藏状态',  status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 6, name: '公告类型',     code: 'announcement_type',           description: '公告类型',       status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 7, name: '公告发布状态', code: 'announcement_publish_status', description: '公告的发布状态', status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8, name: '公告优先级',   code: 'announcement_priority',       description: '公告优先级',     status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10, name: '部门类别',   code: 'department_category',   description: '部门类别',           status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 11, name: '请假类型',   code: 'leave_type',            description: '请假申请的类型（业务示例）', status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12, name: 'AI 点踩理由', code: 'ai_dislike_reason',    description: 'AI 对话点踩时的理由选项', status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 13, name: 'AI 敏感词', code: 'ai_sensitive_word',     description: 'AI 对话输入侧敏感词过滤词库（配合 ai_content_filter_enabled 开关）', status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
];

// ─── 字典项 ───────────────────────────────────────────────────────────────────

export const SEED_DICT_ITEMS: DictItem[] = [
  // 通用状态 (dictId: 1)
  { id: 1,  dictId: 1, label: '启用',   value: 'enabled',      color: 'green',  sort: 1, status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2,  dictId: 1, label: '禁用',   value: 'disabled',     color: 'grey',   sort: 2, status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
  // 菜单类型 (dictId: 3)
  { id: 3,  dictId: 3, label: '目录',   value: 'directory',    color: 'blue',   sort: 1, status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4,  dictId: 3, label: '菜单',   value: 'menu',         color: 'green',  sort: 2, status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 5,  dictId: 3, label: '按钮',   value: 'button',       color: 'orange', sort: 3, status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
  // 用户性别 (dictId: 4)
  { id: 6,  dictId: 4, label: '男',     value: 'male',         color: 'blue',   sort: 1, status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 7,  dictId: 4, label: '女',     value: 'female',       color: 'pink',   sort: 2, status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 8,  dictId: 4, label: '保密',   value: 'secret',       color: 'grey',   sort: 3, status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
  // 显示状态 (dictId: 5)
  { id: 9,  dictId: 5, label: '显示',   value: 'show',         color: 'green',  sort: 1, status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 10, dictId: 5, label: '隐藏',   value: 'hidden',       color: 'grey',   sort: 2, status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
  // 公告类型 (dictId: 6)
  { id: 11, dictId: 6, label: '通知',   value: 'notice',       color: 'blue',   sort: 1, status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 12, dictId: 6, label: '公告',   value: 'announcement', color: 'cyan',   sort: 2, status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 13, dictId: 6, label: '警告',   value: 'warning',      color: 'orange', sort: 3, status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
  // 公告发布状态 (dictId: 7)
  { id: 14, dictId: 7, label: '草稿',   value: 'draft',        color: 'grey',   sort: 1, status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 15, dictId: 7, label: '已发布', value: 'published',    color: 'green',  sort: 2, status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 16, dictId: 7, label: '已撤回', value: 'recalled',     color: 'orange', sort: 3, status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
  // 公告优先级 (dictId: 8)
  { id: 17, dictId: 8, label: '低',     value: 'low',          color: 'grey',   sort: 1, status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 18, dictId: 8, label: '中',     value: 'medium',       color: 'blue',   sort: 2, status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 19, dictId: 8, label: '高',     value: 'high',         color: 'red',    sort: 3, status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
  // 公告发布状态扩展 (dictId: 7)
  { id: 24, dictId: 7, label: '定时发布', value: 'scheduled',   color: 'blue',   sort: 4, status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
  // 部门类别 (dictId: 10)
  { id: 25, dictId: 10, label: '集团',   value: 'group',       color: 'purple', sort: 1, status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 26, dictId: 10, label: '公司',   value: 'company',     color: 'blue',   sort: 2, status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 27, dictId: 10, label: '部门',   value: 'department',  color: 'green',  sort: 3, status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
  // 请假类型 (dictId: 11)
  { id: 28, dictId: 11, label: '年假',   value: 'annual',      color: 'green',  sort: 1, status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 29, dictId: 11, label: '病假',   value: 'sick',        color: 'orange', sort: 2, status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 30, dictId: 11, label: '事假',   value: 'personal',    color: 'blue',   sort: 3, status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 31, dictId: 11, label: '婚假',   value: 'marriage',    color: 'pink',   sort: 4, status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 32, dictId: 11, label: '其他',   value: 'other',       color: 'grey',   sort: 5, status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
  // AI 点踩理由 (dictId: 12)
  { id: 33, dictId: 12, label: '不准确', value: 'inaccurate',  color: 'red',    sort: 1, status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 34, dictId: 12, label: '不相关', value: 'irrelevant',  color: 'orange', sort: 2, status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 35, dictId: 12, label: '有害信息', value: 'harmful',   color: 'violet', sort: 3, status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 36, dictId: 12, label: '其他',   value: 'other',       color: 'grey',   sort: 4, status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
  // AI 敏感词 (dictId: 13) —— 示例词条，value 即敏感词本身
  { id: 37, dictId: 13, label: '示例敏感词', value: '示例敏感词', color: 'red', sort: 1, status: 'enabled', createdAt: SEED_DATE, updatedAt: SEED_DATE },
];

// ─── 限流规则 ─────────────────────────────────────────────────────────────────

export const SEED_RATE_LIMIT_RULES = [
  {
    name: 'analytics-ingest',
    description: '匿名埋点事件上报限流',
    windowMs: 60 * 1000,
    limit: 120,
    keyType: 'ip' as const,
    enabled: true,
    blockedMessage: '埋点上报过于频繁，请稍后再试',
    pathPatterns: [],
    createdAt: SEED_DATE,
    updatedAt: SEED_DATE,
  },
  {
    name: 'error-report',
    description: '匿名前端错误上报限流',
    windowMs: 60 * 1000,
    limit: 60,
    keyType: 'ip' as const,
    enabled: true,
    blockedMessage: '错误上报过于频繁，请稍后再试',
    pathPatterns: [],
    createdAt: SEED_DATE,
    updatedAt: SEED_DATE,
  },
  {
    name: 'replay-ingest',
    description: '会话回放分片上报限流',
    windowMs: 60 * 1000,
    limit: 60,
    keyType: 'ip' as const,
    enabled: true,
    blockedMessage: '回放上报过于频繁，请稍后再试',
    pathPatterns: [],
    createdAt: SEED_DATE,
    updatedAt: SEED_DATE,
  },
  {
    name: 'workflow_public_callback',
    description: '工作流公开回调接口限流',
    windowMs: 60 * 1000,
    limit: 120,
    keyType: 'ip_path' as const,
    enabled: true,
    blockedMessage: '工作流回调请求过于频繁，请稍后再试',
    pathPatterns: [
      '/api/public/workflow/external-callback/*',
      '/api/public/workflow/trigger-callback/*',
    ],
    createdAt: SEED_DATE,
    updatedAt: SEED_DATE,
  },
  {
    name: 'report_public_share',
    description: '报表公开分享访问限流（无需登录，防滥用/防爆破）',
    windowMs: 60 * 1000,
    limit: 120,
    keyType: 'ip' as const,
    enabled: true,
    blockedMessage: '访问过于频繁，请稍后再试',
    pathPatterns: ['/api/report/public/*'],
    createdAt: SEED_DATE,
    updatedAt: SEED_DATE,
  },
  {
    name: 'payment_public_link',
    description: '公开支付链接下单限流',
    windowMs: 60 * 1000,
    limit: 10,
    keyType: 'ip_path' as const,
    enabled: true,
    blockedMessage: '支付请求过于频繁，请稍后再试',
    pathPatterns: [],
    createdAt: SEED_DATE,
    updatedAt: SEED_DATE,
  },
  {
    name: 'chat_send',
    description: '聊天消息发送限流（按用户）',
    windowMs: 60 * 1000,
    limit: 60,
    keyType: 'user' as const,
    enabled: true,
    blockedMessage: '消息发送过于频繁，请稍后再试',
    pathPatterns: [],
    createdAt: SEED_DATE,
    updatedAt: SEED_DATE,
  },
  {
    name: 'ai_chat_send',
    description: 'AI 对话发送限流（按用户）',
    windowMs: 60 * 1000,
    limit: 15,
    keyType: 'user' as const,
    enabled: true,
    blockedMessage: 'AI 对话过于频繁，请稍后再试',
    pathPatterns: [],
    createdAt: SEED_DATE,
    updatedAt: SEED_DATE,
  },
  {
    name: 'ai_share_view',
    description: 'AI 对话分享页访问限流（无需登录，防滥用）',
    windowMs: 60 * 1000,
    limit: 60,
    keyType: 'ip' as const,
    enabled: true,
    blockedMessage: '访问过于频繁，请稍后再试',
    pathPatterns: [],
    createdAt: SEED_DATE,
    updatedAt: SEED_DATE,
  },
];

// ─── 定时任务 ─────────────────────────────────────────────────────────────────

export const SEED_CRON_JOBS: CronJob[] = [
  {
    id: 1,
    name: '清理过期验证码',
    cronExpression: '0 */30 * * * *',
    handler: 'cleanExpiredCaptchas',
    params: null,
    status: 'enabled',
    description: '每30分钟清理过期的验证码',
    retryCount: 0,
    retryInterval: 0,
    retryBackoff: false,
    monitorTimeout: null,
    lastRunAt: '2024-01-01 00:30:00',
    lastRunStatus: 'success',
    lastRunMessage: null,
    createdAt: SEED_DATE,
    updatedAt: SEED_DATE,
  },
  {
    id: 4,
    name: '定时公告自动发布',
    cronExpression: '*/5 * * * *',
    handler: 'publishScheduledAnnouncements',
    params: null,
    status: 'enabled',
    description: '每 5 分钟检查并自动发布到期的定时公告',
    retryCount: 0,
    retryInterval: 0,
    retryBackoff: false,
    monitorTimeout: null,
    lastRunAt: null,
    lastRunStatus: null,
    lastRunMessage: null,
    createdAt: SEED_DATE,
    updatedAt: SEED_DATE,
  },
  {
    id: 5,
    name: '清理过期终端录屏',
    cronExpression: '0 4 * * *',
    handler: 'cleanupTerminalRecordings',
    params: null,
    status: 'enabled',
    description: '每天凌晨 4 点根据系统配置（保留天数 / 容量上限）自动清理终端录屏',
    retryCount: 0,
    retryInterval: 0,
    retryBackoff: false,
    monitorTimeout: null,
    lastRunAt: null,
    lastRunStatus: null,
    lastRunMessage: null,
    createdAt: SEED_DATE,
    updatedAt: SEED_DATE,
  },
  {
    id: 33,
    name: 'SSL 证书到期巡检',
    cronExpression: '0 0 9 * * *',
    handler: 'sslCertificateInspection',
    params: null,
    status: 'enabled',
    description: '每天 9 点巡检 SSL 证书，即将过期（30 天内）或已过期时通知管理员',
    retryCount: 0,
    retryInterval: 0,
    retryBackoff: false,
    monitorTimeout: null,
    lastRunAt: null,
    lastRunStatus: null,
    lastRunMessage: null,
    createdAt: SEED_DATE,
    updatedAt: SEED_DATE,
  },
  {
    id: 34,
    name: '运维主机探测',
    cronExpression: '0 */5 * * * *',
    handler: 'probeOpsHosts',
    params: null,
    status: 'enabled',
    description: '每 5 分钟探测启用的运维主机，更新在线状态与资源快照（概览矩阵数据源）',
    retryCount: 0,
    retryInterval: 0,
    retryBackoff: false,
    monitorTimeout: null,
    lastRunAt: null,
    lastRunStatus: null,
    lastRunMessage: null,
    createdAt: SEED_DATE,
    updatedAt: SEED_DATE,
  },
  {
    id: 6,
    name: '补投支付事件',
    cronExpression: '0 * * * * *',
    handler: 'dispatchPaymentEvents',
    params: null,
    status: 'enabled',
    description: '每分钟补投支付/退款成功的 outbox 事件，确保进程崩溃后履约不丢失',
    retryCount: 0,
    retryInterval: 0,
    retryBackoff: false,
    monitorTimeout: null,
    lastRunAt: null,
    lastRunStatus: null,
    lastRunMessage: null,
    createdAt: SEED_DATE,
    updatedAt: SEED_DATE,
  },
  {
    id: 7,
    name: '关闭过期支付订单',
    cronExpression: '0 */5 * * * *',
    handler: 'closeExpiredPaymentOrders',
    params: null,
    status: 'enabled',
    description: '每5分钟关闭已过期仍未支付的订单',
    retryCount: 0,
    retryInterval: 0,
    retryBackoff: false,
    monitorTimeout: null,
    lastRunAt: null,
    lastRunStatus: null,
    lastRunMessage: null,
    createdAt: SEED_DATE,
    updatedAt: SEED_DATE,
  },
  {
    id: 8,
    name: '支付对账',
    cronExpression: '0 */10 * * * *',
    handler: 'paymentReconciliation',
    params: null,
    status: 'enabled',
    description: '每10分钟对支付中的订单主动查单，纠正状态（回调兜底）',
    retryCount: 0,
    retryInterval: 0,
    retryBackoff: false,
    monitorTimeout: null,
    lastRunAt: null,
    lastRunStatus: null,
    lastRunMessage: null,
    createdAt: SEED_DATE,
    updatedAt: SEED_DATE,
  },
  {
    id: 9,
    name: '行为数据每日聚合',
    cronExpression: '0 0 1 * * *',
    handler: 'analyticsRollupDaily',
    params: '7',
    status: 'enabled',
    description: '每天 01:00 重建近 7 天埋点每日聚合（趋势提速；窗口冗余以容忍数日停机）',
    retryCount: 1,
    retryInterval: 60,
    retryBackoff: false,
    monitorTimeout: null,
    lastRunAt: null,
    lastRunStatus: null,
    lastRunMessage: null,
    createdAt: SEED_DATE,
    updatedAt: SEED_DATE,
  },
  {
    id: 11,
    name: '错误告警评估',
    cronExpression: '0 */5 * * * *',
    handler: 'evaluateErrorAlerts',
    params: null,
    status: 'enabled',
    description: '每5分钟评估错误告警规则并触发通知',
    retryCount: 0,
    retryInterval: 0,
    retryBackoff: false,
    monitorTimeout: null,
    lastRunAt: null,
    lastRunStatus: null,
    lastRunMessage: null,
    createdAt: SEED_DATE,
    updatedAt: SEED_DATE,
  },
  {
    id: 12,
    name: '系统指标采样',
    cronExpression: '0 * * * * *',
    handler: 'sampleSystemMetrics',
    params: null,
    status: 'enabled',
    description: '每分钟将系统监控指标快照落库，用于历史趋势与容量规划',
    retryCount: 0,
    retryInterval: 0,
    retryBackoff: false,
    monitorTimeout: null,
    lastRunAt: null,
    lastRunStatus: null,
    lastRunMessage: null,
    createdAt: SEED_DATE,
    updatedAt: SEED_DATE,
  },
  {
    id: 13,
    name: '监控告警评估',
    cronExpression: '30 * * * * *',
    handler: 'evaluateMonitorAlerts',
    params: null,
    status: 'enabled',
    description: '每分钟评估系统监控告警规则，达阈触发、恢复解除',
    retryCount: 0,
    retryInterval: 0,
    retryBackoff: false,
    monitorTimeout: null,
    lastRunAt: null,
    lastRunStatus: null,
    lastRunMessage: null,
    createdAt: SEED_DATE,
    updatedAt: SEED_DATE,
  },
  {
    id: 19,
    name: '报表订阅推送分发',
    cronExpression: '30 * * * * *',
    handler: 'dispatchReportSubscriptions',
    params: null,
    status: 'enabled',
    description: '每分钟扫描启用的报表订阅，按各自 Cron 判断到期并推送仪表盘指标摘要（邮件/站内信）',
    retryCount: 0,
    retryInterval: 0,
    retryBackoff: false,
    monitorTimeout: null,
    lastRunAt: null,
    lastRunStatus: null,
    lastRunMessage: null,
    createdAt: SEED_DATE,
    updatedAt: SEED_DATE,
  },
  {
    id: 20,
    name: '报表物化快照刷新',
    cronExpression: '15 * * * * *',
    handler: 'refreshReportMaterializations',
    params: null,
    status: 'enabled',
    description: '每分钟扫描启用物化的数据集，按各自 Cron 判断到期并刷新快照（给大屏/高频报表降压）',
    retryCount: 0,
    retryInterval: 0,
    retryBackoff: false,
    monitorTimeout: null,
    lastRunAt: null,
    lastRunStatus: null,
    lastRunMessage: null,
    createdAt: SEED_DATE,
    updatedAt: SEED_DATE,
  },
  {
    id: 21,
    name: '报表数据预警评估',
    cronExpression: '45 * * * * *',
    handler: 'dispatchReportAlerts',
    params: null,
    status: 'enabled',
    description: '每分钟扫描启用的数据预警规则，按各自 Cron 判断到期并评估阈值，触发时通知（站内信/邮件）',
    retryCount: 0,
    retryInterval: 0,
    retryBackoff: false,
    monitorTimeout: null,
    lastRunAt: null,
    lastRunStatus: null,
    lastRunMessage: null,
    createdAt: SEED_DATE,
    updatedAt: SEED_DATE,
  },
  {
    id: 22,
    name: '重试失败分账单',
    cronExpression: '0 */10 * * * *',
    handler: 'retryFailedSharing',
    params: null,
    status: 'enabled',
    description: '每10分钟重试渠道调用失败的分账单（渠道未受理且未达重试上限），防止分账单永久卡在失败态',
    retryCount: 0,
    retryInterval: 0,
    retryBackoff: false,
    monitorTimeout: null,
    lastRunAt: null,
    lastRunStatus: null,
    lastRunMessage: null,
    createdAt: SEED_DATE,
    updatedAt: SEED_DATE,
  },
  {
    id: 23,
    name: 'T+1 自动结算',
    cronExpression: '0 10 1 * * *',
    handler: 'generateDailySettlements',
    params: null,
    status: 'enabled',
    description: '每日 01:10 为昨日账期按渠道×租户自动生成结算批次（无交易跳过，已生成幂等跳过）',
    retryCount: 0,
    retryInterval: 0,
    retryBackoff: false,
    monitorTimeout: null,
    lastRunAt: null,
    lastRunStatus: null,
    lastRunMessage: null,
    createdAt: SEED_DATE,
    updatedAt: SEED_DATE,
  },
  {
    id: 24,
    name: '同步待执行与处理中转账单',
    cronExpression: '0 */5 * * * *',
    handler: 'syncPaymentTransfers',
    params: null,
    status: 'enabled',
    description: '每5分钟恢复已审批未提交渠道的转账，并查询处理中或结果未知转账的终态',
    retryCount: 0,
    retryInterval: 0,
    retryBackoff: false,
    monitorTimeout: null,
    lastRunAt: null,
    lastRunStatus: null,
    lastRunMessage: null,
    createdAt: SEED_DATE,
    updatedAt: SEED_DATE,
  },
  {
    id: 25,
    name: '自动拉取渠道账单对账',
    cronExpression: '0 0 2 * * *',
    handler: 'autoPaymentRecon',
    params: null,
    status: 'enabled',
    description: '每日 02:00 拉取昨日渠道账单自动对账（沙箱渠道生成模拟账单；已有批次跳过）',
    retryCount: 0,
    retryInterval: 0,
    retryBackoff: false,
    monitorTimeout: null,
    lastRunAt: null,
    lastRunStatus: null,
    lastRunMessage: null,
    createdAt: SEED_DATE,
    updatedAt: SEED_DATE,
  },
  {
    id: 27,
    name: '执行到期签约代扣',
    cronExpression: '0 * * * * *',
    handler: 'executeDueDeductions',
    params: null,
    status: 'enabled',
    description: '每分钟扫描已签约且到期的代扣协议执行周期扣款（失败次日重试，达上限自动暂停）',
    retryCount: 0,
    retryInterval: 0,
    retryBackoff: false,
    monitorTimeout: null,
    lastRunAt: null,
    lastRunStatus: null,
    lastRunMessage: null,
    createdAt: SEED_DATE,
    updatedAt: SEED_DATE,
  },
  {
    id: 28,
    name: '同步渠道交易投诉',
    cronExpression: '0 */5 * * * *',
    handler: 'syncPaymentDisputes',
    params: null,
    status: 'enabled',
    description: '每5分钟拉取渠道投诉单（沙箱渠道对近期成功订单生成模拟投诉，演示用）',
    retryCount: 0,
    retryInterval: 0,
    retryBackoff: false,
    monitorTimeout: null,
    lastRunAt: null,
    lastRunStatus: null,
    lastRunMessage: null,
    createdAt: SEED_DATE,
    updatedAt: SEED_DATE,
  },
  {
    id: 30,
    name: '用户分群定时刷新',
    cronExpression: '0 30 3 * * *',
    handler: 'analyticsSegmentRefresh',
    params: null,
    status: 'enabled',
    description: '每天凌晨 3:30 重算全部启用中的用户分群成员快照，避免分群人群与触达名单静默过期',
    retryCount: 1,
    retryInterval: 300,
    retryBackoff: false,
    monitorTimeout: null,
    lastRunAt: null,
    lastRunStatus: null,
    lastRunMessage: null,
    createdAt: SEED_DATE,
    updatedAt: SEED_DATE,
  },
  {
    id: 31,
    name: '补投通知事件',
    cronExpression: '0 * * * * *',
    handler: 'dispatchNotifications',
    params: null,
    status: 'enabled',
    description: '每分钟补投通知中心 outbox 中待派发的事件，并取走免打扰时段结束后到期的延后投递',
    retryCount: 0,
    retryInterval: 0,
    retryBackoff: false,
    monitorTimeout: null,
    lastRunAt: null,
    lastRunStatus: null,
    lastRunMessage: null,
    createdAt: SEED_DATE,
    updatedAt: SEED_DATE,
  },
  {
    id: 32,
    name: '聚合通知摘要',
    cronExpression: '0 */10 * * * *',
    handler: 'aggregateNotificationDigests',
    params: null,
    status: 'enabled',
    description: '每 10 分钟把到期的摘要通知按收件人合并成一封汇总邮件（摘要模式为每小时/每日的用户）',
    retryCount: 0,
    retryInterval: 0,
    retryBackoff: false,
    monitorTimeout: null,
    lastRunAt: null,
    lastRunStatus: null,
    lastRunMessage: null,
    createdAt: SEED_DATE,
    updatedAt: SEED_DATE,
  },
  {
    id: 35,
    name: '回放会话收尾',
    cronExpression: '*/5 * * * *',
    handler: 'finalizeStaleReplays',
    params: null,
    status: 'enabled',
    description: '每 5 分钟把闲置超时（标签页被杀等）的 recording 回放会话标记为已结束',
    retryCount: 0,
    retryInterval: 0,
    retryBackoff: false,
    monitorTimeout: null,
    lastRunAt: null,
    lastRunStatus: null,
    lastRunMessage: null,
    createdAt: SEED_DATE,
    updatedAt: SEED_DATE,
  },
];

// ─── 标签 ─────────────────────────────────────────────────────────────────────

export const SEED_TAGS: Tag[] = [
  { id: 1, name: '重要',   color: '#ef4444', groupName: '优先级',   description: '高优先级事项',    status: 'enabled', sortOrder: 1, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2, name: '紧急',   color: '#f97316', groupName: '优先级',   description: '需要立即处理',    status: 'enabled', sortOrder: 2, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 3, name: '普通',   color: '#6b7280', groupName: '优先级',   description: '常规事项',        status: 'enabled', sortOrder: 3, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 4, name: '新用户', color: '#2563eb', groupName: '用户标签', description: '新注册用户',      status: 'enabled', sortOrder: 1, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 5, name: 'VIP',    color: '#a855f7', groupName: '用户标签', description: 'VIP 会员用户',   status: 'enabled', sortOrder: 2, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 6, name: '待处理', color: '#f59e0b', groupName: '状态标签', description: '等待处理的事项', status: 'enabled', sortOrder: 1, createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 7, name: '已完成', color: '#10b981', groupName: '状态标签', description: '已完成的事项',   status: 'enabled', sortOrder: 2, createdAt: SEED_DATE, updatedAt: SEED_DATE },
];

// ─── 数据脱敏规则 ─────────────────────────────────────────────────────────────

export const SEED_DATA_MASK_CONFIGS: DataMaskConfig[] = [
  { id: 1, entity: 'user', field: 'phone',  label: '手机号',   maskType: 'phone',   customRule: null, exemptRoleCodes: ['super_admin'], enabled: true,  remark: '手机号脱敏，超管豁免',           createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 2, entity: 'user', field: 'email',  label: '邮箱',     maskType: 'email',   customRule: null, exemptRoleCodes: ['super_admin'], enabled: true,  remark: '邮箱脱敏，超管豁免',             createdAt: SEED_DATE, updatedAt: SEED_DATE },
  { id: 3, entity: 'user', field: 'idCard', label: '身份证号', maskType: 'id_card', customRule: null, exemptRoleCodes: ['super_admin'], enabled: false, remark: '身份证脱敏规则（示例，默认禁用）', createdAt: SEED_DATE, updatedAt: SEED_DATE },
];

// ─── 监控告警规则 ─────────────────────────────────────────────────────────────
// 开箱即用的默认规则：基础设施容量兜底 + 各业务域最值得盯的失效信号。
// 全部默认走站内信（接收用户为管理员 ID=1），部署方按需在「告警中心」改阈值 / 加邮件与 Webhook。
// durationMinutes 用于抑制毛刺：比率型指标必须持续超阈才触发，避免一次抖动就打扰值班。
export const SEED_MONITOR_ALERT_RULES: Array<{
  id: number;
  name: string;
  metric: MonitorMetric;
  operator: MonitorAlertOperator;
  threshold: number;
  durationMinutes: number;
  level: MonitorAlertLevel;
  channels: string[];
  recipientUserIds: number[];
  recipientEmails: string[];
  silenceMinutes: number;
  enabled: boolean;
}> = [
  // 基础设施
  { id: 1, name: 'CPU 使用率过高',        metric: 'cpu',                       operator: 'gte', threshold: 85,  durationMinutes: 5,  level: 'warning',  channels: ['inapp'], recipientUserIds: [1], recipientEmails: [], silenceMinutes: 30, enabled: true },
  { id: 2, name: '内存使用率过高',        metric: 'memory',                    operator: 'gte', threshold: 90,  durationMinutes: 5,  level: 'warning',  channels: ['inapp'], recipientUserIds: [1], recipientEmails: [], silenceMinutes: 30, enabled: true },
  { id: 3, name: '磁盘空间不足',          metric: 'disk',                      operator: 'gte', threshold: 90,  durationMinutes: 0,  level: 'critical', channels: ['inapp'], recipientUserIds: [1], recipientEmails: [], silenceMinutes: 120, enabled: true },
  { id: 4, name: 'HTTP 错误率异常',       metric: 'errorRate',                 operator: 'gte', threshold: 5,   durationMinutes: 3,  level: 'critical', channels: ['inapp'], recipientUserIds: [1], recipientEmails: [], silenceMinutes: 30, enabled: true },
  { id: 17, name: '事件循环阻塞',         metric: 'loopLag',                   operator: 'gte', threshold: 200, durationMinutes: 3,  level: 'warning',  channels: ['inapp'], recipientUserIds: [1], recipientEmails: [], silenceMinutes: 30, enabled: true },
  { id: 15, name: '日志错误频率异常',     metric: 'logErrorPerMin',            operator: 'gte', threshold: 10,  durationMinutes: 3,  level: 'critical', channels: ['inapp'], recipientUserIds: [1], recipientEmails: [], silenceMinutes: 30, enabled: true },
  { id: 16, name: '日志警告频率异常',     metric: 'logWarnPerMin',             operator: 'gte', threshold: 30,  durationMinutes: 5,  level: 'warning',  channels: ['inapp'], recipientUserIds: [1], recipientEmails: [], silenceMinutes: 60, enabled: true },
  // 流程引擎
  { id: 5, name: '流程引擎健康分过低',    metric: 'workflowHealth',            operator: 'lt',  threshold: 60,  durationMinutes: 5,  level: 'warning',  channels: ['inapp'], recipientUserIds: [1], recipientEmails: [], silenceMinutes: 60, enabled: true },
  { id: 6, name: '流程作业出现死信',      metric: 'workflowDeadLetter',        operator: 'gte', threshold: 1,   durationMinutes: 0,  level: 'warning',  channels: ['inapp'], recipientUserIds: [1], recipientEmails: [], silenceMinutes: 120, enabled: true },
  // 支付
  { id: 7, name: '支付失败率飙升',        metric: 'paymentFailureRate',        operator: 'gte', threshold: 20,  durationMinutes: 5,  level: 'critical', channels: ['inapp'], recipientUserIds: [1], recipientEmails: [], silenceMinutes: 30, enabled: true },
  { id: 8, name: '支付卡单堆积',          metric: 'paymentStuckPaying',        operator: 'gte', threshold: 10,  durationMinutes: 0,  level: 'critical', channels: ['inapp'], recipientUserIds: [1], recipientEmails: [], silenceMinutes: 60, enabled: true },
  { id: 9, name: '对账差异待处理',        metric: 'paymentReconDiff',          operator: 'gte', threshold: 1,   durationMinutes: 0,  level: 'warning',  channels: ['inapp'], recipientUserIds: [1], recipientEmails: [], silenceMinutes: 720, enabled: true },
  { id: 10, name: '支付事件派发积压',     metric: 'paymentEventBacklog',       operator: 'gte', threshold: 20,  durationMinutes: 0,  level: 'critical', channels: ['inapp'], recipientUserIds: [1], recipientEmails: [], silenceMinutes: 60, enabled: true },
  { id: 11, name: '支付回调投递失败率高', metric: 'paymentWebhookFailureRate', operator: 'gte', threshold: 30,  durationMinutes: 10, level: 'warning',  channels: ['inapp'], recipientUserIds: [1], recipientEmails: [], silenceMinutes: 60, enabled: true },
  // 开放平台
  { id: 12, name: '开放 API 错误率异常',  metric: 'openApiErrorRate',          operator: 'gte', threshold: 10,  durationMinutes: 5,  level: 'warning',  channels: ['inapp'], recipientUserIds: [1], recipientEmails: [], silenceMinutes: 30, enabled: true },
  { id: 13, name: '单应用错误率异常',     metric: 'openApiAppErrorRate',       operator: 'gte', threshold: 50,  durationMinutes: 10, level: 'warning',  channels: ['inapp'], recipientUserIds: [1], recipientEmails: [], silenceMinutes: 60, enabled: true },
  { id: 14, name: '应用订阅被自动停用',   metric: 'openWebhookDisabledSubs',   operator: 'gte', threshold: 1,   durationMinutes: 0,  level: 'warning',  channels: ['inapp'], recipientUserIds: [1], recipientEmails: [], silenceMinutes: 720, enabled: true },
  { id: 18, name: '回放存储接近配额',     metric: 'replayStorageMb',           operator: 'gte', threshold: 3277, durationMinutes: 0,  level: 'warning',  channels: ['inapp'], recipientUserIds: [1], recipientEmails: [], silenceMinutes: 720, enabled: true },
];

// ─── 意见反馈初始数据 ─────────────────────────────────────────────────────────
export const SEED_USER_FEEDBACKS: UserFeedback[] = [
  { id: 1, userId: 1, userNickname: '管理员', score: 5, category: 'suggestion', content: '整体体验很流畅，希望列表页支持自定义每页条数的默认值', pagePath: '/system/users', replayId: null, status: 'resolved', handleRemark: '已在偏好设置中支持', handledBy: 1, handlerNickname: '管理员', handledAt: '2024-01-02 10:00:00', createdAt: SEED_DATE, updatedAt: '2024-01-02 10:00:00' },
  { id: 2, userId: 1, userNickname: '管理员', score: 3, category: 'bug', content: '导出中心偶尔出现任务状态不刷新的情况，需要手动点刷新', pagePath: '/system/export-jobs', replayId: null, status: 'processing', handleRemark: '排查中，疑似 WS 断线重连问题', handledBy: 1, handlerNickname: '管理员', handledAt: '2024-01-03 15:30:00', createdAt: '2024-01-03 09:00:00', updatedAt: '2024-01-03 15:30:00' },
  { id: 3, userId: 1, userNickname: '管理员', score: 4, category: 'ux', content: '暗色模式下部分图表文字对比度偏低', pagePath: '/', replayId: null, status: 'pending', handleRemark: null, handledBy: null, handlerNickname: null, handledAt: null, createdAt: '2024-01-05 14:20:00', updatedAt: '2024-01-05 14:20:00' },
  { id: 4, userId: 1, userNickname: '管理员', score: null, category: 'other', content: '建议文档站增加全文搜索', pagePath: '/system/settings', replayId: null, status: 'ignored', handleRemark: '文档站已有搜索入口', handledBy: 1, handlerNickname: '管理员', handledAt: '2024-01-06 11:00:00', createdAt: '2024-01-06 08:45:00', updatedAt: '2024-01-06 11:00:00' },
];
